### ISSUE TITLE
inline images

### ISSUE THREAD

**Issue by sney** [ivaldi/brimir#120]
Apologies if this feature exists already; I don't see it documented anywhere.

Most of the tickets we receive include a screenshot or a photo. Is it possible to have these images appear in or below the body of the ticket, rather than having to download them?

**Comment by fiedl** [comment]
See also: https://github.com/ivaldi/brimir/commit/9979ee265f10781c77d79074d558ce6d2527fb11#commitcomment-13045769

**Comment by frenkel** [comment]
This has just been added to master.
