### ISSUE TITLE
Integration with Devise

### ISSUE THREAD

**Issue by nahtnam** [ivaldi/brimir#139]
Hey!

I was wondering how well this would integrate with an already existing rails app with Devise?

Thanks.

**Comment by frenkel** [comment]
I'm not sure what you mean. Do you want to re-use the users table of another application?

**Comment by nahtnam** [comment]
Yeah, pretty much so that we can integrate the brimir with our own website.

**Comment by frenkel** [comment]
I don't know, I haven't tried. It will probably be difficult to let it connect to two databases: one for your devise table, the other for the rest.

**Comment by nahtnam** [comment]
Ok, thanks.
