### ISSUE TITLE
Signing in using Google accounts (based on Omniauth)

### ISSUE THREAD

**Issue by FloHin** [ivaldi/brimir#140]
As there is this feature request on the road map and I am currently working with omniauth I would be happy to take care of that.

I wanted to discuss, how exactly should that be archieved? As there is no registration form and omniauth should not invite masses of new users,  I assumed the following:

- Not registered user cannot use omniauth to login/register
- Signed in users may goto their control panel (users/2/edit) and connect with those omniauth providers
- Afterwards, "connected" users can sign in through omniauth (google so far)

Biggest problems and/or discussion points are:
- Where should the buttons be placed?
- What texts are needed?
- How should an unallowed omniauth signin attempt be handled?

Best regards,
Flo

**Comment by frenkel** [comment]
Thank you very much for the pull request. I think your assumptions are correct, we'd better be to restricted than to "open".
I'll have time to review and merge your pull-request on friday, so stay tuned :)

**Comment by FloHin** [comment]
You are welcome, hope my assumptions and prototype implementations are useful.
PR was updated! I added houndci improvments and translations

**Comment by frenkel** [comment]
Thanks for fixing that. I'll review and merge friday :)

**Comment by FloHin** [comment]
Thank you very much for reviewing, fixing my mistakes and finishing it! You could have notified me and I would have of course polished it myself, but I understand this was faster and more efficient. 

I was unaware if the default devise-omniauth config instead of middleware-omniauth could handle the multiple identities. thanks for re-cleaning controllers and auth_filters, this style is far more compatible, gonna remember that.

Hope it was helpful anyway and if omniauth needs more features/fixes or I can participate in this case any further, let me know.

(issue is closeable imho)

**Comment by frenkel** [comment]
Hi, thanks for your reply. I'm glad you whould want to fix those problems yourself. Most pull-request I've seen end up being unused because the original author doesn't feel like cleaning up the feedback he gets.

The pull request was very useful and I'm glad you took the time to create it.
