### ISSUE TITLE
No method for TicketMailer.notify_assigned

### ISSUE THREAD

**Issue by drummerroma** [ivaldi/brimir#143]
There is no such method in TicketMailer.

[3] pry(main)> TicketMailer.notify_assigned(@ticket).deliver
NoMethodError: undefined method `notify_assigned' for TicketMailer:Class
from /Users/alex/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/actionmailer-4.1.8/lib/action_mailer/base.rb:553:in `method_missing'

**Comment by frenkel** [comment]
Thanks, I've fixed it in `master`
