### ISSUE TITLE
undefined method `assignee=' for #<Reply:0x007f8e38a6be68>

### ISSUE THREAD

**Issue by drummerroma** [ivaldi/brimir#144]
in app/models/rule.rb line 58

If rule is working on a response object method should be Response.user

elsif action_operation == 'assign_user'
      user = User.where(email: action_value).first
      unless user.nil?
        ticket.assignee = user
        ticket.save
      end
    end
  end

**Comment by frenkel** [comment]
Thanks for you report. I've fixed the problem (rules should only be applied to tickets).
