### ISSUE TITLE
"Can't verify CSRF token authenticity" warning in the log

### ISSUE THREAD

**Issue by pineapple-thief** [ivaldi/brimir#146]
Hi! Looks like there is a bug in master branch

In layouts/application.html.erb
<%= csrf_meta_tags %> 
I've just noticed this warning in the production log 'Can't verify CSRF token authenticity'
I've changed the line to
<%= csrf_meta_tag %>
and warnings are gone. Must be something with different method names for different Rails versions? I'm on 4.1.9

**Comment by frenkel** [comment]
That does not solve the warning, because they do the same (see: http://api.rubyonrails.org/classes/ActionView/Helpers/CsrfHelper.html#method-i-csrf_meta_tag)

You're probably seeing this on ticket create from an email and not from the web interface.

**Comment by frenkel** [comment]
Posted to soon: could you paste the log entries?

**Comment by pineapple-thief** [comment]
Oops, you are right. Silly me)

2015-01-21 1:40 GMT+10:00 Frank Groeneveld <notifications@github.com>:

**Comment by pineapple-thief** [comment]
Processing by TicketsController#create as JSON
  Parameters: {"message"=>"From support@paperlinxsales.nl  Tue Jan 20 10:43:10 2015\nReturn-Path: <support@paperlinxsales.nl>\nX-Original-To: miranda.brinkmans@paperlinxsales.nl\nDelivered-
Can't verify CSRF token authenticity

It seem to happen on json post as you predicted

**Comment by frenkel** [comment]
I've fixed it in `master`, so the error should not occur anymore. Thanks for your report!
