### ISSUE TITLE
Add logging for replies#create transaction?

### ISSUE THREAD

**Issue by pineapple-thief** [ivaldi/brimir#147]
Errors inside transaction happen silently, which isn't very convenient. Maybe add some logging?

```ruby
rescue => e
  Rails.logger.error "Exception occured on Reply transaction!"
  Rails.logger.error "message: #{e.message}"
  Rails.logger.error "backtrace: #{e.backtrace.join("\n")}"
  render action: 'new'
end
```

I have lots of stuff happening in my branch in one commit at once, so I don't know how to submit PR with just those changes, that's why the issue

**Comment by frenkel** [comment]
Thanks, I've added it!
