### ISSUE TITLE
TicketsController#create should limit access to IP and be user/pass protected

### ISSUE THREAD

**Issue by cthiel** [ivaldi/brimir#149]
Creating and Replying to tickets via the tickets.json API is currently open to the world. This should get locked down by eg. checking request.remote_ip and/or by adding authenticate_with_http_basic around the creation of tickets.

**Comment by frenkel** [comment]
Why would you want to restrict that? I don't understand why you would allow somebody to create tickets by e-mail but not using the JSON API.

You can also create tickets from anywhere without an account by visiting <yourbrimirurl>/tickets/new. Would you want to disallow that as well?

**Comment by cthiel** [comment]
My motivation for locking it down, and probably also disable tickets/new for non logged-in users is the fact, that I would be using brimir only for managing incoming ticket mails. Those mails are also spam-filtered already by the mail provider, which is a nice addition.

**Comment by frenkel** [comment]
Ok, so you don't want to prevent the creation of tickets by everybody, but you want to filter for spam. I'll add it to the feature request list in the README and close this issue report. Somebody might implement it in the future.

Thanks for trying and helping to improve Brimir!
