### ISSUE TITLE
error when trying to install via openshift

### ISSUE THREAD

**Issue by jeanfrancis** [ivaldi/brimir#151]
Hi,

I have the below error when trying to install via openshift :MySQL 5.1 database added.  Please make note of these credentials:

       Root User: 
   Root Password: 
   Database Name: support

Connection URL: mysql://$OPENSHIFT_MYSQL_DB_HOST:$OPENSHIFT_MYSQL_DB_PORT/

You can manage your new MySQL database by also embedding phpmyadmin.
The phpmyadmin username and password will be the same as the MySQL credentials above.
The initial build for the application failed: Shell command '/sbin/runuser -s /bin/sh 54c3bda74382ec51cb000219 -c "exec /usr/bin/runcon 'unconfined_u:system_r:openshift_t:s0:c4,c488' /bin/sh -c \"gear postreceive --init >> /tmp/initial-build.log 2>&1\""' returned an error. rc=255

.Last 10 kB of build output:
Stopping Ruby cartridge
Stopping MySQL 5.1 cartridge
Repairing links for 1 deployments
Building git ref 'master', commit 2db73d8
Building Ruby cartridge
bundle install --deployment --path ./app-root/repo/vendor/bundle
NOTE: You can prevent installing certain Gemfile group using: rhc env set BUNDLE_WITHOUT=groupname
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/..
Could not find http_accept_language-2.0.3 in any of the sources
An error occurred executing 'gear postreceive' (exit code: 7)
Error message: CLIENT_ERROR: Failed to execute: 'control build' for /var/lib/openshift/54c3bda74382ec51cb000219/ruby

For more details about the problem, try running the command again with the '--trace' option.

**Comment by frenkel** [comment]
Fixed in master. Please try again and let me know when it's still broken.
