### ISSUE TITLE
Integrate with Opsweekly

### ISSUE THREAD

**Issue by jeanfrancis** [ivaldi/brimir#152]
is it possible to integrate with Opsweekly https://github.com/etsy/opsweekly to get reporting for Emails on Opsweekly

**Comment by frenkel** [comment]
What kind of integration do you want? I'm not familiair with opsweekly and don't know what it would need/want.

**Comment by jeanfrancis** [comment]
Be able to get (via API ?) on Opsweekly stats of ticket (response time,owner...)

**Comment by frenkel** [comment]
I've added it to the feature request list. We ourselves have no experience with opsweekly, but maybe somebody comes along and adds it. Thanks for helping improve the project!
