### ISSUE TITLE
Social media implementation?

### ISSUE THREAD

**Issue by karibuTW** [ivaldi/brimir#154]
Hi guys,

I'm wondering if managing Twitter, Facebook and others social medias will be part of Brimir later?
Several non-free (As free speech) solutions offers this and it's quite handy.

Nice project otherwise!

Thanks

**Comment by frenkel** [comment]
Interesting idea! Could you comment with some links of other systems?

**Comment by karibuTW** [comment]
Sure,

The helpdesk account can be linked to a Twitter and/or Facebook account and it will work the a similar way than with emails.
For Twitter, it will check any mention of TAGs you are following and you will be able to reply as you do for emails.

For example, there are:
http://freshdesk.com/customer-engagement/social-customer-service
https://www.bornevia.com/
https://www.zoho.com/support/social-integration.html
http://www.deskero.com/en/helpdesksoftware

And many others.

Hope it helps!

**Comment by frenkel** [comment]
Great. I'll add this to the feature request list. Let's hope somebody finds the time to build it!
