### ISSUE TITLE
Close ticket window if status changes to "deleted" or "closed"

### ISSUE THREAD

**Issue by drummerroma** [ivaldi/brimir#162]
I would prefer to close the ticket.show when status changes to deleted or closed and turn back to the tickets-list.
Simple add the following code to /views/tickets/update.js.erb

<% if params[:ticket][:status] == "deleted" || params[:ticket][:status] == "closed" %>
    window.location = "<%= tickets_path %>";
<% end %>

**Comment by frenkel** [comment]
Sorry, but we won't add that, because it would be really confusing when the user clicks the wrong status. He would then need to manually re-search for the ticket to fix the status.
