### ISSUE TITLE
Use references instead of message-id to thread notification mails

### ISSUE THREAD

**Issue by frenkel** [ivaldi/brimir#163]
Because message-id should be unique in an inbox.

**Comment by fiedl** [comment]
Maybe another reason to change the thread-recognition method: We just had a client whose email client did not send the `In-Reply-To` header, and therefore the original ticket could not be identified.

What do you have in mind when you say "references"? Some token or id in the subject? Or maybe some token in the original message footer, prefixed by "Do not delete this line:"?

**Comment by frenkel** [comment]
No this is the `References` header. Mail clients which ignore `In-Reply-To` will unfortunately also ignore `References` headers, so it won't solve your problem. Your problem would be solved by this item on the Feature Request List:

- Switchable property to support threads by using special tags in the subject line instead of relying on mail headers.

It can be implemented by adding a unique id in the body of the email, that the customer should not remove.

**Comment by fiedl** [comment]
Thanks for the clarification!

**Comment by git-jls** [comment]
@fiedl, are you still interested in this feature?

**Comment by fiedl** [comment]
No, using the message id has worked so far pretty well for us. And for the few cases where it doesn't work, we have the merge-tickets feature, now.
