### ISSUE TITLE
Issue with a CC field

### ISSUE THREAD

**Issue by 0x3333** [ivaldi/brimir#168]
I have searched and found an issue that has been closed(Fixed) to add CC field.

But this fix has been reverted in commit b45f5f55b3af86626b3b97d2019dbf4fb41a9d6c.

I'd like to know if CC field is possible.

Some issues have to notify more than one person.

Thanks!

**Comment by frenkel** [comment]
This was possible, but then the notifications changed completely and we've not implemented CC functionality again. We do want to add it though, so it'll come back sometime.

**Comment by 0x3333** [comment]
I see. Thanks!

**Comment by basschoen** [comment]
We've just added this.

**Comment by fiedl** [comment]
Nice! :)
