### ISSUE TITLE
Issue with dropdown

### ISSUE THREAD

**Issue by PatoSoft** [ivaldi/brimir#169]
I have an issue with the dropdown of the top bar (where you can sign_out or edit user). I can´t click those links inside the dropdown, some jQuery select2 error I think. 

I can click these links if they are out the dropdown, directly in the bar.

Thanks and excuse my English >.<

**Comment by frenkel** [comment]
You probably didn't precompile the javascript, or your server is not sending them. Do you see errors in the console of the browser webinspector? 404's maybe?

**Comment by PatoSoft** [comment]
Thanks you!
