### ISSUE TITLE
Using QuillJS as the rich text editor

### ISSUE THREAD

**Issue by ApfelUser** [ivaldi/brimir#172]
I'd love to see Brimir using [QuillJS Rich Text Editor](http://quilljs.com/) instead of the old, crappy looking :smile: [TinyMCE](http://www.tinymce.com/)

**Comment by frenkel** [comment]
Looks nice! I'll have a look at it this week.

**Comment by krazyjakee** [comment]
An alternative is [Redactor](http://imperavi.com/redactor/) but QuillJS looks fine. Anything is better than tinymce.

**Comment by ApfelUser** [comment]
:+1: [Redactor](http://imperavi.com/redactor/) seems also like a very good editor.

**Comment by ApfelUser** [comment]
Any updates?

**Comment by frenkel** [comment]
No sorry, we haven't finished implementing the new design yet.

**Comment by ApfelUser** [comment]
Okay, no problem :smile: Just wanted to know if this is still WIP

**Comment by smgdkngt** [comment]
Does anybody know of a quilljs gem which is a bit up to date? https://github.com/the-robear/quill-rails is quite outdated.

**Comment by frenkel** [comment]
Added to the feature request list.
