### ISSUE TITLE
Language defaulting to Chinese

### ISSUE THREAD

**Issue by aFreshMelon** [ivaldi/brimir#176]
And I have no idea how to fix it.

**Comment by AAbouZaid** [comment]
I have installed Brimir today and I have the same issue. Brimir read English as Chinese.
![brimir_language_issue_20150325 | height = 250px ](https://cloud.githubusercontent.com/assets/6760103/6833152/9765279e-d333-11e4-9827-59b04113ef25.png)

**Comment by frenkel** [comment]
Should be fixed now, incorrect contribution slipper through. Thanks for reporting.
