### ISSUE TITLE
Default locale for non-logged in users regardless of user-agent

### ISSUE THREAD

**Issue by modsaid** [ivaldi/brimir#179]
Currently the locale is obtained from the user-agent headers

app/controllers/application_controller.rb:56

```
 I18n.locale = http_accept_language.compatible_language_from(locales)
```

But sometimes (like in my case)  I need to set a default locale that is not english (Arabic in my case) and I want that to load even if the user-agent accepted english by default

Setting the default locale in the standard way in application.rb will not be of value

```
    config.i18n.default_locale = :ar
```

I think there should be a way to force that.

**Comment by frenkel** [comment]
Closed by pull-request #180.
