### ISSUE TITLE
Message saving crashed is content is too long

### ISSUE THREAD

**Issue by JanneMantyharju** [ivaldi/brimir#181]
Datatype for message content (in MySQL) is text, which permits 65k messages. If the message size exceeds this, saving the message will crash. This happened to me after faulty email settings, which caused mail server to send back the message with attachment in message body.
There should be handling to check message size and/or datatype should be changed to longtext.

**Comment by frenkel** [comment]
Thanks for reporting, we use PostgreSQL which uses a 1GB limit. This is now fixed in `master`.
