### ISSUE TITLE
Brimir should recognize undelivered mail messages

### ISSUE THREAD

**Issue by JanneMantyharju** [ivaldi/brimir#182]
It would be handy to recognize mail server error messages. Otherwise in case of undeliverable mail message sent back to ticket address, mail loop will occur.

**Comment by RCM7** [comment]
+1 to this. Happened to me in a postfix misconfiguration, then I had to kill the app so it would stop the loop.

**Comment by frenkel** [comment]
To me this seems rather difficult to solve, because there is not one format for those bounce emails. Could you post post an example of your bounce email? I'll try to find a good solution to this.

**Comment by cthiel** [comment]
Maybe http://www.rubydoc.info/github/mikel/mail/Mail/Message#bounced%3F-instance_method will just work fine for this use case?

**Comment by frenkel** [comment]
Great, didn't know that one, thanks!

So what would be the best workaround? No notifications for bounced mails?

**Comment by RCM7** [comment]
Maybe a one time notification? E.g. Customer quota is full and email from brimir got bounced. Brimir puts notification on topic but doesn't send the email again to where it was bounced (avoiding the loop).

**Comment by frenkel** [comment]
Yeah, only adding the bounce message to the ticket (if that can be recognized, otherwise create a new ticket) and not sending any notification for it seems the most reasonable. I'll try to implement it.

**Comment by frenkel** [comment]
I added support for this using `bounced?` and also using empty `Return-Path` recognition. It seems Gmail uses that last one because their mails are not recognized by `bounced?`.

**Comment by RCM7** [comment]
Nice! Thanks :)
