### ISSUE TITLE
updating ticket status, priotity and assignee not possible

### ISSUE THREAD

**Issue by flokli** [ivaldi/brimir#183]
When showing a single ticket, I'm not able to update the ticket status, priority and assignee, although the controls seem to be hyperlinks. Its only possible to add Labels.

**Comment by frenkel** [comment]
Does the logout button work? If not, you're javascripts are probably not served (or incorrectly)

**Comment by flokli** [comment]
The logout button also doesn't work, however assigning agents via the index page works (which should also be javascript).

In the developer console, I receive
```
tickets-a8e4a83d7d85683c384752a016f4ba04.js?body=1:39 Uncaught TypeError: undefined is not a function
application-9c9534baa61a25ccf0fed3b9516372d4.js?body=1:55966 Uncaught TypeError: undefined is not a function
```

...so I think it seems to be a javascript issue.

I ran `rake assets:precompile` (without `ENV=production`) and started the development environment with `rails server`. This should normally work, right?

**Comment by flokli** [comment]
The javascript calls are related to `select2()` being called. Probably the library is not loaded yet when this code gets executed?

**Comment by frenkel** [comment]
In the development version, you do not want to run assets:precompile. Try again after removing `public/assets` and restarting the server.

**Comment by flokli** [comment]
Yop, this one worked. Thanks!
