### ISSUE TITLE
add a plaintext mail mode

### ISSUE THREAD

**Issue by flokli** [ivaldi/brimir#184]
It would be nice if brimir would support sending and receiving plaintext-only mails.
In this case, the wysiwyg-editor could also be disabled.

When receiving an HTML Mail, it should load the plaintext version of it (if available) or convert the HTML version to text otherwise.

I think this setting would make most sense be a global one (probably in settings.yml)

**Comment by nshopik** [comment]
I assume recent commit 62b50f9d6655b1404b93e0a4294e861742bbc9cc add such option now

**Comment by frenkel** [comment]
Yes, forgot to report here. We've added it in a per-user fashion. There is still a bug with some text overflowing when there is no hard line ending, but other than that it works fine so far.

**Comment by nshopik** [comment]
@frenkel I did test with plaintext mode enabled, and it appears it still sending both plaintext version and HTML as Content-Type: multipart/alternative; but HTML editor was disabled, is this intended?

**Comment by frenkel** [comment]
I've originally added it like that because the receiving party might prefer HTML. Would you prefer not to send any HTML at all?

**Comment by nshopik** [comment]
Yeah, plaintext it actually preferable in some scenarios
