### ISSUE TITLE
The counter is not displayed correctly

### ISSUE THREAD

**Issue by Mayccoll** [ivaldi/brimir#186]
version 0.5.0 
commit 9e4f639b920f3
Fresh install
![brimir](https://cloud.githubusercontent.com/assets/2009698/7215723/d6f878ce-e5a9-11e4-8673-933fdce4dea1.png)

**Comment by frenkel** [comment]
@Mayccoll Does it work correctly with commit a7c2c451efbab19043c002aac21973ffd17684cf?

@smgdkngt I thought the new design wouldn't be pushed to master yet, because it wasn't tested that well?

**Comment by Mayccoll** [comment]
commit 9e4f639
No counter
![brimir-bug](https://cloud.githubusercontent.com/assets/2009698/7225022/65a4a4d4-e6ff-11e4-984e-3f23c33769b3.png)

**Comment by frenkel** [comment]
The problem was a new design that should not be committed yet. We'll improve that, meanwhile I've reset master to a correct working version.
