### ISSUE TITLE
TinyMCE doesn't appear

### ISSUE THREAD

**Issue by wilkersena** [ivaldi/brimir#187]
After install brimir, the TinyMCE text editor does not appear when I click on new ticket, the field contents are displayed only the tags < p > </ p>

**Comment by frenkel** [comment]
Assets are probably not precompiled. Is the logout button broken as well?

-----Oorspronkelijk bericht-----
Van: "wilkersena" <notifications@github.com>
Verzonden: ‎29-‎4-‎2015 21:43
Aan: "ivaldi/brimir" <brimir@noreply.github.com>
Onderwerp: [brimir] TinyMCE doesn't appear (#187)

After install brimir, the TinyMCE text editor does not appear when I click on new ticket, the field contents are displayed only the 
</ p>

**Comment by wilkersena** [comment]
Yes, the logout button does not work. What do i need to do?

**Comment by frenkel** [comment]
Follow the steps in the README and precompile the assets :)

-----Oorspronkelijk bericht-----
Van: "wilkersena" <notifications@github.com>
Verzonden: ‎29-‎4-‎2015 22:36
Aan: "ivaldi/brimir" <brimir@noreply.github.com>
CC: "Frank Groeneveld" <frank@ivaldi.nl>
Onderwerp: Re: [brimir] TinyMCE doesn't appear (#187)

Yes, the logout button does not work. What do i need to do?
