### ISSUE TITLE
Allow Pre-Defined answers

### ISSUE THREAD

**Issue by ascora** [ivaldi/brimir#190]
Allow to answer  ticket with a pre-defined answer. Agentsa should be able to select between a range of pre-defined answers

**Comment by frenkel** [comment]
Thanks for your suggestion. It was on the requested features list as "When replying, select a response from pre-defined canned responses and modify to your needs" already, so I'm closing this one.

**Comment by svoop** [comment]
Brimir would be a perfect match if it featured canned replies. Too bad this feature is so far down the wishlist. I might help implement it at some point (I'm a Ruby/Rails dev), however, it's quite a big one and right now another OSS pet project is eating all my spare time. 😢 

Have to stick to OpenSupports for now, despite it's many ugly bugs.

**Comment by svoop** [comment]
@frenkel 

On second regard, Tthis may be quite a low hanging fruit. How about using email templates for this? The UI to edit them is complete, all it takes is a new kind "canned answer" and a dropdown in the reply form to select one of the canned answers which is then simply copied into the reply form for submission.

This shouldn't be too much work to do and sufficient for many cases. And it could always be converted into a full fledged answers archive later on.

What do you think?

**Comment by frenkel** [comment]
Sure, that was the plan. We don't have time or incentive to implement it ourselves though, so it would have to be a community contribution by someone else.

**Comment by svoop** [comment]
By using the existing email templates infrastructure, the feature shrinks considerably. I invested an hour yesterday to implement this, after adding a few tests you'll get a PR.

However, care to re-open this issue to track progres?

**Comment by svoop** [comment]
@frenkel Here we go: PR #435
