### ISSUE TITLE
no success docker version.

### ISSUE THREAD

**Issue by kt1024** [ivaldi/brimir#191]
every build in docker hub marked as 'error'.

**Comment by frenkel** [comment]
The docker build is not maintained anymore, the build fail because the `Dockerfile` was removed from the repository. I'll remove the image from Docker Hub to avoid further confusion. Thanks for reporting this.

**Comment by lenovouser** [comment]
Any particular reason for not supporting Docker anymore? Would like to use Docker instead of installing it somewhere :smile:

**Comment by frenkel** [comment]
Yes, we are not using it ourselves, so it is difficult to maintain. If you want to use and maintain it, I'll be happy to merge pull requests for it.
