### ISSUE TITLE
Broken text indention with new design

### ISSUE THREAD

**Issue by fiedl** [ivaldi/brimir#193]
When introducing user avatars in pull request #189, I've pointed out that the indention of the text (i.e. placing the text *beside* the avatar) makes the conversation easier to read.

> The optical separation of replies is more intuitive with avatars: It's harder to miss a reply when scrolling fast. And it looks more like a conversation view.

However, with the new design in `upstream/master`, this layout feature has been removed again.

I've opened a separate issue for this, in order to have a place to discuss it, since, of course, this is a matter of opinion.

In general, **I would really prefer a layout where the avatars are *left of* the text**, like it is in this very github conversation, or, as shown in this quick mockup (**I prefer the layout on the left-hand side**):

![bildschirmfoto 2015-06-18 um 00 00 49](https://cloud.githubusercontent.com/assets/1679688/8219835/20dfd022-154d-11e5-8488-fc657c84b7a5.png)

What do you think?

Best wishes,
Sebastian

**Comment by frenkel** [comment]
![screenshot from 2015-06-18 08 02 34](https://cloud.githubusercontent.com/assets/121169/8225093/975439f8-1590-11e5-9ba2-c894929d5376.png)

You're proposing we add a margin to the left of the text in my screenshot, right? I think that would be a great optimization on desktop browser, however what would you propose to do on small screen devices such as tablets or mobile phones?

**Comment by fiedl** [comment]
Yes, I agree.

## Desktops

We've already tried this in production on desktops. It has really increased the clarity of arrangement. 
This is a screenshot from #189, that is, with the old design, not the new one, but you'll get the idea:

![Screenshot from #189](https://cloud.githubusercontent.com/assets/1679688/7641915/33578d74-fa8d-11e4-8c29-1cf74b14716c.png)

## Tablets

It also looks good on tablets:

![img_2859](https://cloud.githubusercontent.com/assets/1679688/8230869/73516d30-15c4-11e5-9247-a88c47fb181d.jpg)
 
![img_2858](https://cloud.githubusercontent.com/assets/1679688/8230876/7fd7b140-15c4-11e5-8e3d-3f7603173c1e.jpg)

## Mobiles

On mobiles, indeed, this looks like wasting space.

![bildschirmfoto 2015-06-18 um 14 27 52](https://cloud.githubusercontent.com/assets/1679688/8231093/3ce66be0-15c6-11e5-8234-d90898ad7ced.png)

But, foundation has support for showing elements depending on the screen size:
http://foundation.zurb.com/docs/components/visibility.html

If you are willing to go in that direction, I could have a look into that.

**Comment by frenkel** [comment]
Yes, we already use some variants for mobile vs desktop. I think adding the indention for `large-` en `medium-` (desktop and tablet) does improve the experience, if we can leave it out for `small-` (phones).

I'll ask our front-end developer whether he can try to implement this in the new design.
*ping @smgdkngt*

**Comment by fiedl** [comment]
Based on the example code from #189,

```
<div class="avatar-left"><%= user_avatar(user) %></div>
<div class="avatar-matter">
  Other Content
  For example, an email of the user.
</div>
```

he "steamroller tactics" would be to add one additional like break that is shown only on small devices:

```
<div class="avatar-left"><%= user_avatar(user) %></div>
<br clear="all" class="show-for-small-only" />
<div class="avatar-matter">
  Other Content
  For example, an email of the user.
</div>
```

This is not elegant, but proves the concept.

**Comment by fiedl** [comment]
I like your result very much. It looks clean and clearly arranged. Therefore, I'm closing this issue. Thanks!

![bildschirmfoto 2015-06-20 um 23 35 51](https://cloud.githubusercontent.com/assets/1679688/8269374/7f931e9e-17a5-11e5-8f43-1b2a39896eb6.png)

One minor suggestion: I would resize the avatar beside the reply form to have the same size as the other reply avatars, i.e. all 32x32.

**Comment by frenkel** [comment]
Good suggestion. According to @smgdkngt this should now be changed as well :)
