### ISSUE TITLE
Delivery failed when receiving a mail

### ISSUE THREAD

**Issue by thehunt33r** [ivaldi/brimir#199]
Hi !

I've been trying to wrap my head around this issue for a good hour... I don't know why those emails are coming back.

Immediately after sending an email to brimir, I get an email saying Delivery has failed to these recipients etc....

So : I have my alias support : 
```bash
support: "|/bin/bash /root/brimir/script/post-mail http://127.0.0.1:3000/tickets.json"
```

When sending a mail to support (using swaks atm, as this server is just a test, I didn't bother with MX records) this is swaks output : 
```bash
<-  250 2.0.0 t6SEGL1U023594 Message accepted for delivery
```
Which leads me to believe the exchange is good (I've got the same output when sending a mail to root@myserver)

When looking at mail.log : 
```bash
Jul 28 10:34:55 brimir sm-mta[24245]: t6SEYrHO024245: from=<matthieu.antoine@domain.com>, size=230, class=0, nrcpts=1, msgid=<201507281434.t6SEYrHO024245@brimir.domain.lan>, proto=ESMTP, daemon=MTA-v4, relay=[10.1.1.140]
Jul 28 10:34:55 brimir sm-mta[24247]: t6SEYrHO024245: Warning: program /bin/sh unsafe: Group writable directory
Jul 28 10:34:55 brimir sm-mta[24246]: t6SEYrHO024245: to="|/bin/bash /root/brimir/script/post-mail http://127.0.0.1:3000/tickets.json", ctladdr=<support@brimir.domain.lan> (8/0), delay=00:00:01, xdelay=00:00:00, mailer=prog, pri=30495, dsn=5.3.0, stat=unknown mailer error 126
Jul 28 10:34:55 brimir sm-mta[24246]: t6SEYrHO024245: t6SEYtHO024246: DSN: unknown mailer error 126
```

I don't know at all where error 126 might be coming from... I understand the unsafe thingy, but it's just a warning so it shouldn't be breaking stuff right ?

Thanks !

Matthieu

**Comment by frenkel** [comment]
What kind of OS is this?
Do you have Bash in `/bin/bash` and do you have `curl` installed?

**Comment by thehunt33r** [comment]
This is Debian 8 (Jessie), and bash is in /bin/bash / curl installed.

**Comment by frenkel** [comment]
What happens if you run something like `echo 'test' | /bin/bash /root/brimir/script/post-mail http://127.0.0.1:3000/tickets.json` on the command line?

**Comment by thehunt33r** [comment]
When issuing ```bash echo 'test' | /bin/bash /root/brimir/script/post-mail http://127.0.0.1:3000/tickets.json ``` , I get no specific output and no new ticket in Brimir.

**Comment by frenkel** [comment]
I think I know your problem: the user that is running your mail server can't access anything under `/root`. Try running it from a normal location instead of the home directory of the root user.

**Comment by thehunt33r** [comment]
You were right ! I moved my install from /root/brimir to /opt and now it works perfectly ! Thanks :+1:
