### ISSUE TITLE
Cannot assign labels to agent accounts after creation.

### ISSUE THREAD

**Issue by reportingbugs** [ivaldi/brimir#201]
When you are first creating a user, you are able to assign labels that give the user access to any ticket with that label by default.

IFF the user type is "Agent," then after the user is added to the database, the option to assign new labels to the user becomes unavailable in the Edit User screen, you are only able to add an email signature.

However, if you change the user type to customer, the "assign label" field becomes active again.

**Comment by frenkel** [comment]
Thanks for your request. I'll add it to the list of requested features and close this report.

**Comment by frenkel** [comment]
We've added support for this in current `master` branch.
