### ISSUE TITLE
Cannot delete users.

### ISSUE THREAD

**Issue by reportingbugs** [ivaldi/brimir#202]
There is no way in the UI to delete agents or customers from the user list.

**Comment by frenkel** [comment]
This has been discussed more than once. What do you want to do with all tickets and replies from a user you delete? They have to be deleted as well, because otherwise you'll lose things like original email address etc. Would that be viable?

**Comment by reportingbugs** [comment]
My suggestion would be to have a stricter separation of concern between Agent and Customer accounts. There could perhaps be one tab for Agent accounts, with two sub-tabs for "Active" and "Disabled" and then another tab for Customer accounts, with two sub tabs for "Active" and "Archived," where active is all Customers with tickets in Open or Waiting status, and "Archived" for all Customers who have no open tickets.
