### ISSUE TITLE
Request: Notification Timers and Timer Events

### ISSUE THREAD

**Issue by reportingbugs** [ivaldi/brimir#203]
It would be fantastic if there were timers and more robust handling rules enabled in the ruleset.

For example, being able to create a ruleset where if a ticket hasn't been assigned or replied to within 1 hour of being received through email, a notification event is triggered that sends a notification to a support supervisor.

Second example: If a customer doesn't reply to a support response within 48 hours then the ticket is automatically moved to the closed queue.

Third example: If a support agent has taken ownership of a ticket but has not provided a support response within 24 hours, the ticket is automatically assigned to a support supervisor.

Being able to create these types of timer based notification and assignment rules would go a long way towards having Brimir become a ticketing system which can meet the needs of larger support teams with heavier ticket queue loads.

**Comment by frenkel** [comment]
Very good suggestions. We've been thinking about this as well. I'll add it to the feature request list.

**Comment by frenkel** [comment]
Added to the feature request list.
