### ISSUE TITLE
Improve INBOX

### ISSUE THREAD

**Issue by nshopik** [ivaldi/brimir#205]
Since INBOX move into 2-line per ticket it seems wasting lot of space. Here minor UI related improvements 
- Move Subject to first line as its most important info and should be first
- Add ticket number on second line with date of creation
- on right show when ticket updated

Here example
```
Subject                           label                                    25 Aug 11:52
#1235 created by example@example.org at 24 Aug 17:24                         unassigned
```

**Comment by frenkel** [comment]
Great suggestion. I've added it in master.
