### ISSUE TITLE
Human friendly (Relative Time) date format in INBOX

### ISSUE THREAD

**Issue by nshopik** [ivaldi/brimir#206]
I rather have more human friendly date format like, 2 hours ago, or 5 days ago for dates in INBOX but still show full ISO date format when you hover mouse over date. Just like Github issues currently have.

This JS may help do it http://momentjs.com/

**Comment by frenkel** [comment]
You mean like we implemented it in the ticket detail page for replies? That should not be very difficult to add, as we already have it there.

**Comment by nshopik** [comment]
Weird, I have same date format in ticket details page like this `August 23, 2015 01:18` as in INBOX

**Comment by nshopik** [comment]
Sorry I was looking into ticket creation date :smile:
