### ISSUE TITLE
Default email adress is not default

### ISSUE THREAD

**Issue by jbx26** [ivaldi/brimir#211]
I have several email adresses. One of them is marked as default sender adress.
The default adress is not shown as selected adress in the combo box for answering a ticket.
So, I think that I have to choose the correct email adress each time I reply to a ticket.

**Comment by frenkel** [comment]
When the user has sent the original ticket to another address, that address will be used. When no address is recognized, or the "new ticket" screen is used, it will use the default address.
It is a bug if you have a reproducible example where this differs.
