### ISSUE TITLE
Retrieve Mail

### ISSUE THREAD

**Issue by tboulogne** [ivaldi/brimir#214]
Hello,

Thanks for your great job. A simple question : how could i retrieve the helpdesk main mail when it is on another server ? 

The pipe solution in alias does not work in this case.

Thanks for suggestion or tips.

regards

**Comment by frenkel** [comment]
Why would that not work? If you install curl and the post-mail script from Brimir you can create the pipe alias on the mail server and let is post to the server that hosts Brimir.
