### ISSUE TITLE
Ability to create custom statuses

### ISSUE THREAD

**Issue by rvollebregt** [ivaldi/brimir#217]
It would be nice to have the ability to add extra statuses to the already existing ones. With this feature you could add different workflow statuses such as Ready for Testing / Ready for Deployment for example as per the company's requirements.

**Comment by mipmip** [comment]
:+1:

**Comment by frenkel** [comment]
That would mean we need to add all statuses to a database table and then we would need ways to determine what you consider to be an open ticket (otherwise new tickets cannot receive the right status).

What status would you need that is currently not available?

**Comment by rvollebregt** [comment]
In that case I would suggest to keep the standard ticket statuses non-editable, since some of the statuses have special meaning to the system, of course. Am I correct in assuming that would solve the point you raised above?

About the new statuses: 
Adding new statuses would have the benefit of allowing a ticket go through a set workflow. A new ticket would come in as an Open ticket in the Inbox. Every morning (for example) the inbox would be processed during a ‘standup’ and tickets would be assigned to different agents to handle the problem or request. In this case an extra status would be useful (such as ‘Planned’), so only new and unprocessed tickets are in the Inbox at all times. This separation helps in determining if a ticket has been responded to or not. 
Further, when the ticket has been solved by the agent, it can be assigned a new status to indicate that it can be tested or deployed, for example. The final step would be to close the ticket. Separation of the different stages in a ticket’s flow also keeps the ticket system clean and tidy.

**Comment by frenkel** [comment]
Alright, that would mean all statuses would have to be moved to the database, because having "hard coded" statuses and database statuses make all the logic too complicated. I'll add your request to the Feature Request List, thanks for helping improve Brimir.

**Comment by rvollebregt** [comment]
Great, thanks for considering the change!
Hopefully we can contribute some more sometime soon. Keep up the good work on Brimir :)! So far it's working great.

**Comment by frenkel** [comment]
By the way, in the mean time you might be able to use labels for this purpose.
