### ISSUE TITLE
Request: Desktop Notifications / Auto-Refresh or Page (Ajax?) Update

### ISSUE THREAD

**Issue by michailsideris-gvf** [ivaldi/brimir#218]
Desktop notifications: show a popup a-la Gmail or Trello whenever a new ticket arrives. Useful for people who do support alongside other projects. 

Auto-Refresh/Ajax Update: add an option to automatically refresh the "Open Tickets" page every X minutes, or, even better, the page automatically shows new tickets without needing to refresh. Right now, when a new ticket arrives and you are on the "Open Tickets" view, you need to either refresh the page or click on the "Open Tickets" link in order to see the new ticket(s).

**Comment by frenkel** [comment]
Added to the feature request list.

**Comment by frenkel** [comment]
A simple auto refresh was added a few weeks ago. It refreshes the page when the browser tab gets focus again.
