### ISSUE TITLE
Unable to save attachments

### ISSUE THREAD

**Issue by stenstad** [ivaldi/brimir#222]
Hi, I am looking at saving attachments, but they do not seem to be saved upon ticket posting. Here is the log:
```
D, [2015-09-25T14:45:27.206041 #17065] DEBUG -- :    (0.2ms)  BEGIN
I, [2015-09-25T14:45:27.212856 #17065]  INFO -- : Command :: file -b --mime '/tmp/2a70a4186130ff6ed8664f1173d1e9db20150925-17065-tqsrsb.jpg'
I, [2015-09-25T14:45:27.222279 #17065]  INFO -- : [paperclip] Content Type Spoof: Filename IMAG0210.jpg (image/jpeg from Headers, [image/jpeg] from Extension), content type discovered from file command: . See documentation to allow this combination.
D, [2015-09-25T14:45:27.224909 #17065] DEBUG -- :    (0.2ms)  ROLLBACK
I, [2015-09-25T14:45:27.228526 #17065]  INFO -- : Command :: file -b --mime '/tmp/2a70a4186130ff6ed8664f1173d1e9db20150925-17065-5skjrf.jpg'
I, [2015-09-25T14:45:27.235711 #17065]  INFO -- : [paperclip] Content Type Spoof: Filename IMAG0210.jpg (image/jpeg from Headers, [image/jpeg] from Extension), content type discovered from file command: . See documentation to allow this combination.
I, [2015-09-25T14:45:27.239270 #17065]  INFO -- : Completed 422 Unprocessable Entity in 1535ms (Views: 1.7ms | ActiveRecord: 7.9ms)
```
I tried to look at the code, and noticed that Paperclip now requires you to validate content types. But it seems we are ignoring this with `do_not_validate_attachment_file_type` in `models/attachment.rb`? So I guess it should work.. But isn't this really bad security wise?

**Comment by frenkel** [comment]
Yes, the content type should not be validated, because it always appears broken for some PDFs. When we upload those they report text/plain as type, which differs from what Paperclip expects. Security wise it doesn't seem a problem to me: our server is not executing anything from those attachments based on content type, we always send the contents of the file. What would be the security problem with that?

With regards to your problem: what OS is this? What Brimir version are you running?

**Comment by stenstad** [comment]
This is Ubuntu 14.04, running the 0.6.0 release. GraphicsMagick and Ghostview installed.

**Comment by frenkel** [comment]
That should work just fine, we use something similar in production.
Could you share the file with me? Or is it private information?

**Comment by stenstad** [comment]
The file is just random JPEG I insert into the mail. Any file has the same outcome as far as I can see. I just tried using a PNG instead (my gravatar) and got basically the same message:

```
D, [2015-09-25T21:35:39.580119 #17065] DEBUG -- :    (0.1ms)  BEGIN
I, [2015-09-25T21:35:39.581115 #17065]  INFO -- : Command :: file -b --mime '/tmp/069c6102becee2b5be1b1b645acc2a7820150925-17065-216h0.png'
I, [2015-09-25T21:35:39.585080 #17065]  INFO -- : [paperclip] Content Type Spoof: Filename 0c1987bd6505f42f95a5d9f610f86224.png (image/png from Headers, [image/png] from Extension), content type discovered from file command: . See documentation to allow this combination.
D, [2015-09-25T21:35:39.586300 #17065] DEBUG -- :    (0.1ms)  ROLLBACK
I, [2015-09-25T21:35:39.587216 #17065]  INFO -- : Command :: file -b --mime '/tmp/069c6102becee2b5be1b1b645acc2a7820150925-17065-x7snt6.png'
I, [2015-09-25T21:35:39.591020 #17065]  INFO -- : [paperclip] Content Type Spoof: Filename 0c1987bd6505f42f95a5d9f610f86224.png (image/png from Headers, [image/png] from Extension), content type discovered from file command: . See documentation to allow this combination.
I, [2015-09-25T21:35:39.592783 #17065]  INFO -- : Completed 422 Unprocessable Entity in 214ms (Views: 0.8ms | ActiveRecord: 3.1ms)
```

One thing I'm noticing.. Is it comparing the string "image/png" with the string "[image/png]"? I.e. with the brackets?

**Comment by frenkel** [comment]
Maybe you should report this to the [Paperclip project](https://github.com/thoughtbot/paperclip/), as it does seem that the comparison is wrong indeed. Also, I don't understand why it is executing these checks when we have them disabled.
