### ISSUE TITLE
Start server

### ISSUE THREAD

**Issue by kobject** [ivaldi/brimir#223]
How do i even start the application?

**Comment by frenkel** [comment]
What part of the installation section do you find unclear?

**Comment by kobject** [comment]
When i do rails server to start the application:
/var/www/brimir/vendor/bundle/ruby/1.9.1/gems/activerecord-4.2.3/lib/active_record/connection_adapters/connection_specification.rb:177:in `rescue in spec': Specified 'sqlite3' for database adapter, but the gem is not loaded. Add `gem 'sqlite3'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord). (Gem::LoadError)

i already added gem sqlite3 to the gemfile. And also i am pretty new to RoR. Do you have a nice installation manual?

**Comment by frenkel** [comment]
In the README we don't advise you to run `rails server` but install nginx or apache with passenger. If you use one on those two links in the README it will explain how to set things up.

-----Oorspronkelijk bericht-----
Van: "kobject" <notifications@github.com>
Verzonden: ‎27-‎9-‎2015 10:11
Aan: "ivaldi/brimir" <brimir@noreply.github.com>
CC: "Frank Groeneveld" <frank@ivaldi.nl>
Onderwerp: Re: [brimir] Start server (#223)

When i do rails server to start the application:
/var/www/brimir/vendor/bundle/ruby/1.9.1/gems/activerecord-4.2.3/lib/active_record/connection_adapters/connection_specification.rb:177:in rescue in spec': Specified 'sqlite3' for database adapter, but the gem is not loaded. Addgem 'sqlite3'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord). (Gem::LoadError)
i already added gem sqlite3 to the gemfile. And also i am pretty new to RoR. Do you have a nice installation manual?

**Comment by kobject** [comment]
So if u have to install Passenger, configure the database an Passenger starts and should work?

**Comment by frenkel** [comment]
You don't start passenger yourself. You start apache or nginx and it will start passenger when needed.
