### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by kobject** [ivaldi/brimir#224]
Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)
  /var/lib/gems/1.9.1/gems/execjs-2.6.0/lib/execjs/runtimes.rb:48:in `autodetect'
  /var/lib/gems/1.9.1/gems/execjs-2.6.0/lib/execjs.rb:5:in `<module:ExecJS>'
  /var/lib/gems/1.9.1/gems/execjs-2.6.0/lib/execjs.rb:4:in `<top (required)>'
  /var/lib/gems/1.9.1/gems/coffee-script-2.4.1/lib/coffee_script.rb:1:in `require'
  /var/lib/gems/1.9.1/gems/coffee-script-2.4.1/lib/coffee_script.rb:1:in `<top (required)>'
  /var/lib/gems/1.9.1/gems/coffee-script-2.4.1/lib/coffee-script.rb:1:in `require'
  /var/lib/gems/1.9.1/gems/coffee-script-2.4.1/lib/coffee-script.rb:1:in `<top (required)>'
  /var/lib/gems/1.9.1/gems/coffee-rails-4.1.0/lib/coffee-rails.rb:1:in `require'
  /var/lib/gems/1.9.1/gems/coffee-rails-4.1.0/lib/coffee-rails.rb:1:in `<top (required)>'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
  /var/www/brimir/config/application.rb:7:in `<top (required)>'
  /var/www/brimir/config/environment.rb:2:in `require'
  /var/www/brimir/config/environment.rb:2:in `<top (required)>'
  /var/www/brimir/config.ru:3:in `require'
  /var/www/brimir/config.ru:3:in `block in <main>'
  /var/lib/gems/1.9.1/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
  /var/lib/gems/1.9.1/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
  /var/www/brimir/config.ru:1:in `new'
  /var/www/brimir/config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:107:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:107:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:153:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:28:in `<main>'

**Comment by ApfelUser** [comment]
@kobject 

```
apt-get install curl
curl --silent --location https://deb.nodesource.com/setup_0.12 | bash -
apt-get install --yes nodejs build-essential
```

**Comment by pengux** [comment]
I've installed Nodejs, but still getting the same error when running brimir.

**Comment by frenkel** [comment]
What happens when you type `node` on the commandline? Can it find the command?

**Comment by pengux** [comment]
Yes it can, I've symlinked nodejs to node also...

**Comment by frenkel** [comment]
An the user that runs Brimir has that in the path?

**Comment by pengux** [comment]
Yes, the user brimir (which runs Brimir) can also call node (which node => /usr/bin/node)

**Comment by frenkel** [comment]
Then you'd better report this to the `execjs` gem project at https://github.com/rails/execjs
