### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by kobject** [ivaldi/brimir#225]
Error ID: 855bee30
  Error details saved to: /tmp/passenger-error-yYNLm7.html
  Message from application: Specified 'sqlite3' for database adapter, but the gem is not loaded. Add `gem 'sqlite3'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord). (Gem::LoadError)
  /usr/brimir/vendor/bundle/ruby/1.9.1/gems/activerecord-4.2.3/lib/active_record/connection_adapters/connection_specification.rb:177:in `rescue in spec'
  /usr/brimir/vendor/bundle/ruby/1.9.1/gems/activerecord-4.2.3/lib/active_record/connection_adapters/connection_specification.rb:174:in `spec'
  /usr/brimir/vendor/bundle/ruby/1.9.1/gems/activerecord-4.2.3/lib/active_record/connection_handling.rb:50:in `establish_connection'
  /usr/brimir/vendor/bundle/ruby/1.9.1/gems/activerecord-4.2.3/lib/active_record/railtie.rb:120:in `block (2 levels) in <class:Railtie>'
  /usr/brimir/vendor/bundle/ruby/1.9.1/gems/activesupport-4.2.3/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
  /usr/brimir/vendor/bundle/ruby/1.9.1/gems/activesupport-4.2.3/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
  /usr/brimir/vendor/bundle/ruby/1.9.1/gems/activesupport-4.2.3/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
  /usr/brimir/vendor/bundle/ruby/1.9.1/gems/activesupport-4.2.3/lib/active_support/lazy_load_hooks.rb:27:in `each'
  /usr/brimir/vendor/bundle/ruby/1.9.1/gems/activesupport-4.2.3/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
  /usr/brimir/vendor/bundle/ruby/1.9.1/gems/activerecord-4.2.3/lib/active_record/railtie.rb:116:in `block in <class:Railtie>'
  /usr/brimir/vendor/bundle/ruby/1.9.1/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `instance_exec'
  /usr/brimir/vendor/bundle/ruby/1.9.1/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `run'
  /usr/brimir/vendor/bundle/ruby/1.9.1/gems/railties-4.2.3/lib/rails/initializable.rb:55:in `block in run_initializers'
  /usr/lib/ruby/1.9.1/tsort.rb:150:in `block in tsort_each'
  /usr/lib/ruby/1.9.1/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
  /usr/lib/ruby/1.9.1/tsort.rb:219:in `each_strongly_connected_component_from'
  /usr/lib/ruby/1.9.1/tsort.rb:182:in `block in each_strongly_connected_component'
  /usr/lib/ruby/1.9.1/tsort.rb:180:in `each'
  /usr/lib/ruby/1.9.1/tsort.rb:180:in `each_strongly_connected_component'
  /usr/lib/ruby/1.9.1/tsort.rb:148:in `tsort_each'
  /usr/brimir/vendor/bundle/ruby/1.9.1/gems/railties-4.2.3/lib/rails/initializable.rb:54:in `run_initializers'
  /usr/brimir/vendor/bundle/ruby/1.9.1/gems/railties-4.2.3/lib/rails/application.rb:352:in `initialize!'
  /usr/brimir/config/environment.rb:5:in `<top (required)>'
  /usr/brimir/config.ru:3:in `require'
  /usr/brimir/config.ru:3:in `block in <main>'
  /usr/brimir/vendor/bundle/ruby/1.9.1/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
  /usr/brimir/vendor/bundle/ruby/1.9.1/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
  /usr/brimir/config.ru:1:in `new'
  /usr/brimir/config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:107:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:107:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:153:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:28:in `<main>'

**Comment by kobject** [comment]
cat Gemfile | grep sql
gem 'pg', group: :postgresql
gem 'mysql2', group: :mysql
gem 'sqlite3', group: :sqlite

**Comment by frenkel** [comment]
You should never use sqlite in production, the README also advises you to chose MySQL or PostgreSQL. Please re-read it and configure all files before starting passenger through Nginx or Apache.

-----Oorspronkelijk bericht-----
Van: "kobject" <notifications@github.com>
Verzonden: ‎28-‎9-‎2015 19:36
Aan: "ivaldi/brimir" <brimir@noreply.github.com>
Onderwerp: [brimir] Passenger start (#225)

Message from application: Specified 'sqlite3' for database adapter, but the gem is not loaded. Add gem 'sqlite3' to your Gemfile (and ensure its version is at the min

**Comment by kobject** [comment]
Fixed Thanks, now when i create a login i cant login...

**Comment by frenkel** [comment]
So, do you get an error message? Or what?

**Comment by kobject** [comment]
When i open the console i create a account. If i create it twice it says it already in use. So it means actually that it works. But when i tried to login i dont get an error.

I did some new db:migration get the following error from Passenger:

  ActiveRecord::SchemaMigration Load (4.4ms)  SELECT "schema_migrations".* FROM "schema_migrations"
App 16828 stderr: /usr/lib/ruby/vendor_ruby/phusion_passenger/preloader_shared_helpers.rb:69:in `fork'
App 16828 stderr: :
App 16828 stderr: Cannot allocate memory - fork(2)
App 16828 stderr:  (
App 16828 stderr: Errno::ENOMEM
App 16828 stderr: )
App 16828 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/preloader_shared_helpers.rb:69:in `accept_and_process_next_client'
App 16828 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/preloader_shared_helpers.rb:139:in `run_main_loop'
App 16828 stderr:       from /usr/share/passenger/helper-scripts/rack-preloader.rb:154:in `<module:App>'
App 16828 stderr:       from /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<module:PhusionPassenger>'
App 16828 stderr:       from /usr/share/passenger/helper-scripts/rack-preloader.rb:28:in `<main>'
[ 2015-09-29 02:23:02.2775 16790/7f9f8c43e700 age/Cor/App/Implementation.cpp:303 ]: Could not spawn process for application /home/kobject/brimir: An error occurred while starting the web application. It exited before signalling successful startup back to Phusion Passenger.
  Error ID: 2098ea9b
  Error details saved to: /tmp/passenger-error-QgjqvX.html
  Message from application: An error occurred while starting the web application. It exited before signalling successful startup back to Phusion Passenger. Please read <a href="https://github.com/phusion/passenger/wiki/Debugging-application-startup-problems">this article</a> for more information about this problem.<br>
<h2>Raw process output:</h2>
(empty)

[ 2015-09-29 02:23:02.2821 16790/7f9f8c43e700 age/Cor/Spa/SmartSpawner.h:726 ]: An error occurred while spawning a process: An error occurred while starting the web application. It exited before signalling successful startup back to Phusion Passenger.
[ 2015-09-29 02:23:02.2825 16790/7f9f8c43e700 age/Cor/Spa/SmartSpawner.h:727 ]: The application preloader seems to have crashed, restarting it and trying again...
App 16872 stdout:
App 16872 stderr: /usr/lib/ruby/vendor_ruby/phusion_passenger/preloader_shared_helpers.rb:69:in `fork'
App 16872 stderr: : Cannot allocate memory - fork(2) (Errno::ENOMEM)
App 16872 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/preloader_shared_helpers.rb:69:in `accept_and_process_next_client'
App 16872 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/preloader_shared_helpers.rb:139:in `run_main_loop'
App 16872 stderr:       from /usr/share/passenger/helper-scripts/rack-preloader.rb:154:in `<module:App>'
App 16872 stderr:       from /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<module:PhusionPassenger>'
App 16872 stderr:       from /usr/share/passenger/helper-scripts/rack-preloader.rb:28:in `<main>'
[ 2015-09-29 02:23:06.1739 16790/7f9f8c43e700 age/Cor/App/Implementation.cpp:303 ]: Could not spawn process for application /home/kobject/brimir: An error occurred while starting the web application. It exited before signalling successful startup back to Phusion Passenger.
  Error ID: 287447a5
  Error details saved to: /tmp/passenger-error-sxVvhe.html
  Message from application: An error occurred while starting the web application. It exited before signalling successful startup back to Phusion Passenger. Please read <a href="https://github.com/phusion/passenger/wiki/Debugging-application-startup-problems">this article</a> for more information about this problem.<br>
<h2>Raw process output:</h2>
(empty)

It looks in my eyes that its using the wrong db. If i check my db its called brimir_test.

**Comment by frenkel** [comment]
To me it looks like you don't have enough memory in that server: `Cannot allocate memory `. Use at least 2GB to be sure.

**Comment by kobject** [comment]
I am seeing its working in development mode, i tried:

passenger start -a 0.0.0.0 -p 3000 -d -e production

But then i gert the following error:

The page you were looking for doesn't exist.

You may have mistyped the address or the page may have moved.

**Comment by frenkel** [comment]
It doesn't help to start in development mode, you need to use production mode with a real database and enough memory in the server to use it.

**Comment by kobject** [comment]
Also as i said it tried to use the command to use it in production mode. But got the eroor that the page doesnt exist.

**Comment by frenkel** [comment]
Yes, but that is not how you normally start passenger, as I stated twice before. Start it normally using nginx and/or apache and see what the logs say. I guess you'll get another memory error.
