### ISSUE TITLE
Different text sizes for different languages

### ISSUE THREAD

**Issue by nshopik** [ivaldi/brimir#226]
INBOX subject have different size of text in different languages, here is example with English and Cyrillic
http://i.imgur.com/Df01dTu.png

I've checked that html says it same size, it is, maybe different font for different languages?

**Comment by frenkel** [comment]
Could you see what happens with both languages in the same subject?

**Comment by nshopik** [comment]
I'm bad at html debug but from dev console in chrome says, `OTS derived font` only font used for rendering English text. And for Cyrillic there now 2 fonts `Arial` and `OTS derived font` so I assume it just switched to arial as original font just doesn't have glyph for Cyrillic symbols

**Comment by frenkel** [comment]
Okay, so we can close this? Or do I understand you incorrectly?

**Comment by nshopik** [comment]
Well I was proposing change font to something that covers more languages, to avoid such UI unconsistence, instead of using font that cover just one.

**Comment by frenkel** [comment]
I don't think we will change it, because there will always be other users which have the same problem for a different language.

**Comment by nshopik** [comment]
My point was use font that can handle all Latin(European) Alphabets, I understand this won't work for Asian languages or Arabic script, which is completely different. Anyway we probably have to patch our version to have Arial for INBOX

**Comment by nshopik** [comment]
@frenkel There google Noto Fonts which quite good cover and have harmonious look and feel across many languages if you willing to consider that eventually to make overall look more consistent 

https://www.google.com/get/noto/

**Comment by frenkel** [comment]
We recently added a custom css url to the settings. Maybe you can create a custom css sheet for these changes?
