### ISSUE TITLE
Allow "to" filter on unregistered "From" emails

### ISSUE THREAD

**Issue by Alex131089** [ivaldi/brimir#227]
I'm testing Brimir (and we're probably adopting it for our non profit organization providing students internet access), so I have a temporary alias which redirects emails to brimir (support-brimir@), and I have added support@ and inscription@ as verified (manually) senders, but the "to" filters are currently not working.

I dig a little (rails console is great for this <3) and foud that this ligne is responsible of the problem : https://github.com/ivaldi/brimir/blob/master/app/mailers/ticket_mailer.rb#L104

Why should Brimir be limited receiving emails from verified senders ? Shouldn't this be 2 differents things ?
And the most important : shouldn't the filter act on the actual "to" address instead of the verified one ?
Not really a big deal, but I'm surprised of this behaviour.

**Comment by frenkel** [comment]
We're not storing the actual to, cc and bcc addresses because we've never needed them. We do store the verified address so we can use it to send replies using that same address. I'll add a feature request to the list to allow filtering on to/cc/bcc.
