### ISSUE TITLE
[Feat. req.] Protect /tickets/new with catpcha for non logged-in users

### ISSUE THREAD

**Issue by Alex131089** [ivaldi/brimir#228]
In the idea of #149, while tickets.json can be protected by the web server* to be used only by the mail server, it could be great to let any users post a ticket but having some spam protection, like with a captcha.

*: if you're interested in some example for documentation, here's our setup : https://redmine.resel.fr/projects/support/wiki/Brimir

**Comment by frenkel** [comment]
Thanks, good suggestion! I've added it to the list of requested features.

**Comment by frenkel** [comment]
This has now been merged into master.
