### ISSUE TITLE
Allow notification to any mail address

### ISSUE THREAD

**Issue by Alex131089** [ivaldi/brimir#229]
Brimir is restricting rules notifications to an existing user (https://github.com/ivaldi/brimir/blob/master/app/models/rule.rb#L45), could it be possible to allow any recipient and/or use another notification type like notify_email ?

Not really a problem actually, we just had to add another agent with the required recipient email, but it is more like a workaround.

**Comment by frenkel** [comment]
Thanks, fixed in `master`
