### ISSUE TITLE
Tenants & Domains

### ISSUE THREAD

**Issue by crr0004** [ivaldi/brimir#235]
Hello,

Just recently been setting up brimir using docker and while I have it running, one issue I have come across is the managing of so called 'tenants'. From what I have gleamed, each 'tenant' relates to the domain that brimir is accessed through. Currently when setting up my database it doesn't get set properly, is there anywhere to set this?

Cheers

Chris

**Comment by frenkel** [comment]
Hello Chris,

Do you need support for separate instances of Brimir using the same codebase & server? If not, you shouldn't worry about tenants and just visit the Brimir instance. It will create 1 tenant which will be used to store your global settings (one of the buttons on the top right).

**Comment by crr0004** [comment]
Hey,

Thanks for getting back to me.

I don't. It just appears that when ever I try to create the service for the
first time, the tenant doesn't get set properly. I've had to insert the
tenant through SQL when setting it up to get around it.

Does brimir expect the database to be local? Mine is sitting in another
container.

I am using passenger, or what ever it is called to serve the files, not
sure if that makes a difference. Can't think of why the tenant isn't
getting set properly.

**Comment by frenkel** [comment]
It is created the first time you visit: https://github.com/ivaldi/brimir/blob/master/app/models/tenant.rb#L38

So when you visit for the first time, it is not there? Or are you checking it earlier in, for example, the Rails console?

**Comment by crr0004** [comment]
It may be getting created in rails console somewhere. I'll have to do some
experiments around my setup and see if it's something I'm doing.

I was just wondering if it's created during setup and I got my answer. I'll
close this off now.

Thank you for your help!
