### ISSUE TITLE
forwarding messages in iOS breaks image inclusion in tickets

### ISSUE THREAD

**Issue by richardvlbt** [ivaldi/brimir#236]
It seems that when an email is forwarded to Brimir from iOS the included image is not included properly.

Example of rendered source code:

    <div>
      <img src="cid:D12302E4-AB87-4AD8-81B7-62D2810118FD"><br>
    </div>

**Comment by frenkel** [comment]
I don't have any experience with iOS, but did you download/show the images in your mail client before clicking forward? If the images were not loaded before forwarding they won't be forwarded in most clients.
Does the ticket contain attachments in Brimir?

**Comment by rvollebregt** [comment]
The message was already downloaded in the client before forwarding. An attachment was added to an email which already contained an image. The newly attached image did not show up, though the other image does show up.
Is there any more info you need?

**Comment by frenkel** [comment]
Would it be possible for you to send it to me? frank-at-ivaldi.nl
