### ISSUE TITLE
Persian RTL implementation

### ISSUE THREAD

**Issue by hadifarnoud** [ivaldi/brimir#237]
I tried to install brimir on local to test Persian translation and add features needed for RTL languages.

due to poor documentation on development installation (It's been a while since I coded in Rails), I was unable to even test Persian translation. the interface lang is still English.

**Comment by frenkel** [comment]
Add a persian translation file in config/locale and change the language in your user preferences.

**Comment by hadifarnoud** [comment]
I have done that but interface is still on English. even turned on `ignore_user_agent_locale: true1

**Comment by frenkel** [comment]
What is your translation file called? Does it not contain en: at the first line?

**Comment by hadifarnoud** [comment]
It's fa.yml (that I translated myself) and starts with fa

want to test and add RTL css as well

**Comment by frenkel** [comment]
I don't understand why it doesn't work for you, it does for me (see screenshot). If you select the language for the user and save it, the `ignore_user_agent_locale` does not have any effect.
Where can I find the repo you are using?
![screenshot from 2015-11-24 08 27 36](https://cloud.githubusercontent.com/assets/121169/11360533/988fbfc8-9285-11e5-8537-c43f1ec13b61.png)

**Comment by hadifarnoud** [comment]
perhaps I missed a step on installation? I installed it locally.

**Comment by frenkel** [comment]
No, I can't imagine how you could achieve a problem like this by missing an installation step. If you visit the user profile page, does it show the language correctly?

**Comment by hadifarnoud** [comment]
no, it was set to English. Changed it to فارسی and it works now. Why my default conf was not considered?

**Comment by frenkel** [comment]
The default is copied as soon as your user account is edited.

**Comment by hadifarnoud** [comment]
@frenkel I see the 'direction:rtl' condition doesn't work very well in application.html.erb

foundation supports rtl properly: http://foundation.zurb.com/sites/docs/v/5.5.3/components/rtl.html

we need a separate css (maybe rtl.css) to load if the language is Arabic or Farsi. I would help fix any style by adding css to that file.

regarding tinyMCE, I've added directionality plugin and RTL LTR buttons. https://gist.github.com/hadifarnoud/ecfddee3a0c947f541b9

I also added tinymce language gem bud didn't work for some reason. not a huge bummer though. feel free to delete `language: 'fa_IR',` I suggest adding `data-locale=<%= I18n.locale %>`  to body tag then retrieve it via jquery for adding these settings to application.js

what I did not figure out was the email templates. what are you using for that? I didn't find any view for it. we probably need to add styling to that part too. please advise me on this one.

**Comment by frenkel** [comment]
Great, where can I see your work? :)

The mail templates can be found in `app/views/notification_mailer`

**Comment by hadifarnoud** [comment]
the thing is, the changes I need to make is somehow make Brimir RTL only. for example, I need to add `$text-direction: rtl;` to `_foundation_and_overrides.scss` for making the whole foundation RTL.

http://foundation.zurb.com/sites/docs/v/5.5.3/components/rtl.html
http://foundation.zurb.com/sites/docs/rtl.html

It works just fine. I committed all these changes [here](https://github.com/hadifarnoud/brimir). feel free to give it a try. 

I want to contribute this back to brimir. however, I don't know how to make these changes based on locale. I need your help here.

**Comment by hadifarnoud** [comment]
this is how it looks
<img width="1199" alt="screen shot 1394-09-12 at 18 08 39" src="https://cloud.githubusercontent.com/assets/589808/11563718/a532513e-99ea-11e5-802e-27c98461e2f6.png">
<img width="1221" alt="screen shot 1394-09-12 at 18 08 32" src="https://cloud.githubusercontent.com/assets/589808/11563722/a769e5e8-99ea-11e5-9f83-bfd8590a3808.png">

**Comment by frenkel** [comment]
Thanks. If foundation has to be reconfigured specifically for RTL then this will not be easy to implement per-user indeed. Too bad, it would be great to support that.

**Comment by hadifarnoud** [comment]
there must be a way. I just don't know enough about Rails to do it.

**Comment by frenkel** [comment]
Well, if you need to modify a Foundation variable, that means the precompiled CSS will be different. We would have to create 2 different precompiled CSS versions of Foundation to support "on-the-fly" switching. Maybe we'll let a front-ender try to do it in a different way and he'll let you know.

**Comment by frenkel** [comment]
@hadifarnoud RTL was just added to `master` by @m1es! Are there any other changes needed? For example other missing translations.

**Comment by hadifarnoud** [comment]
thanks @m1es. 
according to [Foundation docs](http://foundation.zurb.com/sites/docs/v/5.5.3/components/rtl.html), the `lang="fa"` must be set in order to get Foundation RTL properly work. 

btw, you can apply this same patch to other RTL languages like Arabic, Hebrew, Urdu, etc.

I will fix css issues left and will add them to application-rtl.scss

**Comment by frenkel** [comment]
Thanks, I added the lang= attribute.

**Comment by hadifarnoud** [comment]
these items are not in the right place I think.

![brimir](https://cloud.githubusercontent.com/assets/589808/11661347/c8bd511c-9de6-11e5-9858-3768b6d944e4.png)

in some cases, a simple class change will fix it. for example, changing `right` to  `left` would fix the inbox counter align.

I have not added any custom css for these case as I feel it would be a lot cleaner if we change the class based on locale.

thoughts?

**Comment by frenkel** [comment]
Yes, some are pretty difficult, for example the looking glass (blue button in your screenshot) needs different HTML for rtl support. I'm not familiar with how others solve this problem, do you know?

**Comment by hadifarnoud** [comment]
well, you can probably make it as two partials, one for ltr and one for rtl
