### ISSUE TITLE
Brimir hangs on MySQL install 

### ISSUE THREAD

**Issue by Aebian** [ivaldi/brimir#238]
Hi Team,

for some reason the dependencies install hangs on the MySQL part for more then one hour. Any Idea why?
Screen: https://img.aebian.org/brimir%40aebian_onlinewwwsupport.aebian.orgsdc_2015-11-22_18-20-56.png

Not sure if there are any logs I can check for. Thanks

**Comment by frenkel** [comment]
Can you re-start it to try again? It is installing the `mysql2` gem, maybe you can ask there if this is a known problem with their gem.
