### ISSUE TITLE
Search in original mail content AND replies

### ISSUE THREAD

**Issue by rbott** [ivaldi/brimir#240]
Hi,

are there any plans to extend the current search function to cover replies as well? Currently, the search is only performed on the ticket table.

Regards
Rudolph

**Comment by frenkel** [comment]
Hi,

Yes, there has been a long standing feature request for this in the `README`:

- Ticket search that also searches in from field and replies.

We still haven't had the need for this ourselves, so we haven't build it yet, though.
Are you a programmer? Would you be able to add it? I can help if you can't fully get it working.
