### ISSUE TITLE
Is it possible for an agent to create a ticket that a specific user will be able to see?

### ISSUE THREAD

**Issue by bsylvain** [ivaldi/brimir#243]
Is it possible for an agent to create a ticket that a specific user will be able to see? As i am working on creating ticket via API,  i am wondering if this is possible, because currently, the API will use an agent account.

**Comment by frenkel** [comment]
If the user is assigned to notified users, he will be able to see it. Also, you can set `@ticket.user` to the user, he will be the owner and see it as well.

**Comment by bsylvain** [comment]
From what I understand, the notified user will receive a mail, but he will not see the ticket in the inbox.

**Comment by frenkel** [comment]
You're right, I thought having permission was enough (https://github.com/ivaldi/brimir/blob/master/app/models/ability.rb#L43) but the inbox won't show it till I modify the viewable_by scope in the tickets model. I'll do this very soon to fix this bug.

**Comment by bsylvain** [comment]
I experimented a little bit with this change, and it seems it only add notification to the root ticket and that mean only agents.
Currently, when (not agent) charlie is notified mid conversation, he can see the whole Ticket.
I am not sure I fully understand how Notification works, but this may be the way to add it : 

    ticket_ids += Ticket.joins(replies: :notifications).where('notifications.user_id=?',2 ).pluck(:id)

**Comment by frenkel** [comment]
I don't fully understand what your change would fix and where I would need to apply it. Can you please elaborate?

**Comment by bsylvain** [comment]
From what I understand, notifications including all the agents are added in a ticket at creation. No user is notified. There is no other way to add a notification directly to the ticket itself.

When a non-agent (that did not create the ticket) is notified in a ticket reply, the relation between ticket and user is only ticket->reply->notification->user and never ticket->notification->user.

The consequences is that a non agent user will only see tickets created with his mail in the inbox. My modification would allow him to see tickets when he is notified of the ticket after it's creation.

Maybe it is on purpose, as currently an agent can create a ticket in the name of an user.

**Comment by frenkel** [comment]
I understand.

Yes, we did this on purpose. The user can always see his/her own tickets if the `from:` is set correctly. Other tickets can be viewed using the link in the mail, but not from the index.

Do you think it would make more sense to see al tickets the user has access too?
