### ISSUE TITLE
Rule - To Email : contains, never matches.

### ISSUE THREAD

**Issue by deepy** [ivaldi/brimir#247]
Hi,

I've set up a rule: `To email address: contains: sysop. Assign label: ops`
And then proceed to send an email to sysop@my.tld the message arrives and does not get labelled.
Looking at my log I can see `To: sysop@my.tld` and `X-Original-To: sysop@my.tld` and `Delivered-To: sysop@mail.my.tld`.

Other rules seem to work though, if I make one for message contains 'test' and send an email containing 'test' it gets properly labelled.

**Comment by frenkel** [comment]
Hi,

Yes, this only works for "verified email addresses". You will have to add the sysop@my.tld address first using the email address button on the op bar (as agent).
