### ISSUE TITLE
Not able to create tickets when email contains only attachment

### ISSUE THREAD

**Issue by pranavpr** [ivaldi/brimir#253]
Brimir is not creating tickets when email contains only attachment. If email contains body text and attachment, attachment is not saved. Logs show following error:

```
  I, [2016-01-12T14:55:06.927414 #47184]  INFO -- : Completed 500 Internal Server Error in 275ms (ActiveRecord: 21.3ms)
F, [2016-01-12T14:55:06.928399 #47184] FATAL -- :
ArgumentError (string contains null byte):
  app/mailers/ticket_mailer.rb:115:in `receive'
  app/controllers/tickets_controller.rb:142:in `create'
```
I am using the latest pull from master and still getting this error. It seems there was an issue with Rails which was fixed in https://github.com/rails/rails/pull/17680 

Please resolve this issue.

**Comment by frenkel** [comment]
Looks more like an invalid email than a bug on the PG gem. Does a simple plain-text email with the attachment work without problems? What database are you using?

**Comment by pranavpr** [comment]
Well it works for all emails without attachment. I am using PostgreSQL. If email contains both text and attachment, ticket is created without attachment. If email contains only attachment, ticket is not created.

**Comment by frenkel** [comment]
Do you have ImageMagick and ghostscript installed on the server? Is the data directory writable by the Rails app?

**Comment by pranavpr** [comment]
I don't have ImageMagick and ghostscript installed on the server. Is that required? What data directory?

**Comment by frenkel** [comment]
Yes, they are needed to create thumbnails of attachments. There should be a directory called "data" in the root of the rails app (it will be automatically created if possible), where the rails app can save the attachments.

**Comment by pranavpr** [comment]
Well I installed ImageMagick. ghostscript was already installed on server. I can see data folder and it has contents in it. After installing ImageMagick, I restarted the server. Still same issue.

**Comment by frenkel** [comment]
Could you create a test account on getbrimir.com (select 1 agent for free instance) and see if the mail can be send to that instance correctly.

**Comment by pranavpr** [comment]
Created a test account at getbrimir.com and below are my findings:

1. When I send email with just text : Works fine
2. When I send email with just pdf attachment, no text : Undelivered Mail Returned to Sender
3. When I send email with both pdf and text: Tickets get created, no attachment can be seen in Brimir though

**Comment by frenkel** [comment]
Thanks, I'll try to debug this in a few days. I can now easily extract your .eml files to reproduce and fix this locally. I'll let you know when it is fixed.

**Comment by frenkel** [comment]
Apparently Apple Mail generates a content_id for all attachments, even when they are not embedded in the text. We currently only show attachments without content_id, because the ones with content_id are inserted into the text.

**Comment by frenkel** [comment]
If you update your server to latest `master`, all should work well now. Our hosted instance will probably be updated in a few days.
