### ISSUE TITLE
Informations

### ISSUE THREAD

**Issue by DRAKUN** [ivaldi/brimir#256]
Bonjour,
jaimerais d'abord vous feliciter pour cette application.
j'aimerais le mettre en place pour manager mon service help Desk qui est composer de 10 agents.
Quels sont les limites de la version gratuites avant que je ne me lance dans l'installation.

**Comment by frenkel** [comment]
Bonjour,

Les limites de la version gratuites est le nombre de agents (1) et il na pas de personnalisation de la 
adresse e-mail.

Bon chance!
