### ISSUE TITLE
The add+ button to assign a label does not seems to works.

### ISSUE THREAD

**Issue by bsylvain** [ivaldi/brimir#260]
The add button does not works when you try to add a label to a ticket. I have looked in the javascript files but i do not understand how the js is supposed to be triggered.

**Comment by frenkel** [comment]
Foundation handles this. Do you see the popup? Or do you get a # in the url bar after clicking?

**Comment by bsylvain** [comment]
I get a # in the URL. I found how it use data-reveal-id, and the hidden div, and I am comparing my prod working version with the dev, but I have not found the problem yet.

**Comment by frenkel** [comment]
Did you precompile your assets using the command in the readme? Can you load the javascript path in production?

**Comment by bsylvain** [comment]
I have a foundation.reveal-fdc4161d1475614d9c63ee5d7a152c7b.js loaded in my page, and yes, the assets where compiled.

**Comment by frenkel** [comment]
If you type that foundation.reveal in your browser, do you get a correct file?

**Comment by bsylvain** [comment]
Yes, and it shows up in the firefox tools, meaning the file is a valid JS.

**Comment by frenkel** [comment]
Do you have it on all tickets? Of just one specific?

**Comment by bsylvain** [comment]
All of them.

**Comment by bsylvain** [comment]
Maybe this is related? Did you reproduce it? https://github.com/zurb/foundation-sites/issues/7723

**Comment by frenkel** [comment]
I reproduced it. We'll look at it tomorrow.

**Comment by frenkel** [comment]
This is now fixed in `master`.
