### ISSUE TITLE
Ticket merge: Notifications of merged tickets (not replies) are not copied over

### ISSUE THREAD

**Issue by fiedl** [ivaldi/brimir#268]
@frenkel said in https://github.com/ivaldi/brimir/pull/242#issuecomment-208268597 : 
> I just merged two tickets in our Brimir instance. The merge went correct, no error messages, but the new reply doesn't have the original notified users. Would you be able to find out how that is possible?

As I understand you, the notifications of a younger ticket (not a reply of a younger ticket) are not copied over.

It's likely that I've missed this case in the original pull request, since we do not use notifications on incoming new tickets.

And apparently, the test does not cover this case:

```ruby
  # test/models/merged_ticket_test.rb

  test 'merging two tickets and copying over the notifications' do
    client_user = User.where(agent: false).first
    agent_user = User.where(agent: true).first
    first_ticket = Ticket.create subject: "First ticket", content: "I've got a question ...", user_id: client_user.id
    Timecop.travel 2.minutes.from_now
    second_ticket = Ticket.create subject: "Second ticket", content: "I forgot to mention ...", user_id: client_user.id
    Timecop.travel 4.minutes.from_now
    second_reply = second_ticket.replies.create content: "Please send me some more info about ...", user_id: agent_user.id
    second_reply.notified_users << client_user
    
    merged_ticket = MergedTicket.from [first_ticket, second_ticket], current_user: agent_user

    assert merged_ticket.replies.order(:created_at).last.notified_users.include? client_user
  end
```

I'll have a look into that.

## Trace

1. `Tickets::SelectedController#update` calls `Ticket.merge @tickets, current_user: current_user` if `params[:merge] == 'true'`.
2. `Ticket.merge` is just a shortcut and calls `MergedTicket.from separate_tickets, options`.
3. `MergedTicket.from` creates a new instance of `MergedTicket < Ticket` and calls `merge` on it:
4. `MergedTicket#merge`:

  ```ruby
  def merge
    oldest_original_ticket.replies << copies_of_the_replies_of_the_younger_tickets
    oldest_original_ticket.replies << younger_tickets.collect { |ticket| ticket.to_reply }
    younger_tickets.each { |ticket| ticket.create_merge_notice(oldest_original_ticket, current_user) } if current_user
    younger_tickets.each { |ticket| ticket.status = :merged; ticket.save }
    return oldest_original_ticket
  end
  ```

  

5. `oldest_original_ticket.replies << younger_tickets.collect { |ticket| ticket.to_reply }`
6. `Ticket#to_reply`:

   ```ruby
  def to_reply
    Reply.new(
      content: self.content,
      created_at: self.created_at,
      updated_at: self.updated_at,
      user_id: self.user_id,
      message_id: self.message_id,
      content_type: self.content_type,
      raw_message_file_name: self.raw_message_file_name,
      raw_message_content_type: self.raw_message_content_type,
      raw_message_file_size: self.raw_message_file_size,
      raw_message_updated_at: self.raw_message_updated_at,
      attachments: self.attachments.collect { |attachment| attachment.dup }
    )
  end
  ```

**Comment by frenkel** [comment]
Yes, you're right, it only happens with younger tickets being merged. Thanks for looking into this!
