### ISSUE TITLE
Incorrect tickets.message_id and in-reply-to header

### ISSUE THREAD

**Issue by czarnecki** [ivaldi/brimir#270]
I post the new ticket via email. The reply to this ticket has wrong in-reply-to header.

Original message-id is
`<CAM=OTHpwbvvGw1FmP_iTo23=r_J8o_mdAfsr1QDLmwHzgCsjqg@mail.gmail.com>`

and the tickets.message_id in the database is:
`57163008cd532_9cc174f9b821356@web510.webfaction.com.mail`

The in-reply-to header of the reply email is also: `<57163008cd532_9cc174f9b821356@web510.webfaction.com.mail>`

I have checked the raw message (via the eml file download) and it's certainly `...@mail.gmail.com` and there is only one Message-ID header.

What could cause this?

**Comment by frenkel** [comment]
Could you post the complete header line that contains the message-id?

**Comment by czarnecki** [comment]
Please find the entire message here (from eml file): https://gist.github.com/czarnecki/e3b27a34b78e039949231a3a5d07c021

Please find the entire message here (from gmail client):
https://gist.github.com/czarnecki/02d7612cca29735cd40fdcd372626f3d

The Message-ID is different from my previous post but the behavior is the same. Lines are break by CRLF.

**Comment by frenkel** [comment]
Both Message-ID's in your examples are the same. Is it stored differently in the database?

**Comment by czarnecki** [comment]
Yes, in the database: `57164bde6e716_9cc174f9b821950@web510.webfaction.com.mail`.
The raw message from gmail client is the source of mail sent to brimir ('show source' option in Gmail).

`web510.webfaction.com.mail` is my hosting server. Probably at some point in the code message-id is empty and Brimir inserts the newly generated. What file/class is responsible for the incoming message parsing? I don't know rails but I can add some prints to investigate it.

**Comment by frenkel** [comment]
The mails are handled by the [`mail` gem](https://github.com/mikel/mail/), which is used extensively everywhere. I don't think the bug is there. The bug is probably somewhere in our code in `app/mailers/ticket_mailer.rb` or in the storage of the message in `app/models/ticket.rb`.
Thanks!

**Comment by czarnecki** [comment]
It happens in notification_mailer.rb line 44. The ticket message-id is replaced with notification message-id which is different. Maybe setting the Message-ID is ignored by my sendmail/hoster and this is the reason the notification gets new Message-ID and than it's copied to ticket ?

**Comment by frenkel** [comment]
I think you're right. I'll try to write some tests for it tomorrow and fix the bug afterwards.
