### ISSUE TITLE
Add voting to issues

### ISSUE THREAD

**Issue by vmpajares** [ivaldi/brimir#271]
It would be useful if the customers could vote issues.

I'm thinking in the enhancement petitions, but someone could found it useful in other issues too. 

I'll try to do it myself but I never worked wit RoR before. Only python, php, C and bash. So any guide is welcome.

**Comment by frenkel** [comment]
I think our current users wouldn't use something like this (we ourselves wouldn't at least), but if you add this and disable it by default then we'll merge it.
I'm closing this issue to keep the bug count from exploding with enhancement, but please follow up on this report if you have any questions or progress.
