### ISSUE TITLE
Cannot access trashed/deleted tickets

### ISSUE THREAD

**Issue by georgebarbarosie** [ivaldi/brimir#272]
Hello,

I've noticed that tickets are not deleted from the database when marking them as deleted. In the menu there's a "Trashed" entry which points to URL /tickets?status=deleted but when clicking that button we get a server error (500). In the logs we have the following:

```
F, [2016-05-12T17:47:19.192738 #30013] FATAL -- :
ActionView::Template::Error (undefined method `id' for nil:NilClass):
    70:       <div class="priority-<%= ticket.priority %> row ticket bb" style="height: 4em;" data-ticket-url="<%= ticket_url(ticket) %>">
    71:         <div class="medium-6 plxxl v-middle columns">
    72:           <input type="checkbox" value="<%= ticket.id %>" name="id[]" class="no-mb" data-toggle-check />
    73:           <%= user_avatar ticket.user, class: 'avatar left mrl mts mlm', size: 30 %>
    74:           <p class="no-mb text-overflow">
    75:             <% unless ticket.subject.blank? %>
    76:               <a href="<%= ticket_url(ticket) %>">
  app/helpers/avatar_helper.rb:87:in `user_avatar'
  app/views/tickets/index.html.erb:73:in `block (2 levels) in _app_views_tickets_index_html_erb__1495997250244203308_37319620'
  app/views/tickets/index.html.erb:69:in `block in _app_views_tickets_index_html_erb__1495997250244203308_37319620'
  app/views/tickets/index.html.erb:51:in `_app_views_tickets_index_html_erb__1495997250244203308_37319620'
```

We're using release 0.7.0

**Comment by frenkel** [comment]
I think there is a ticket without a valid user in your trash. This should not happen, but it also shouldn't make the interface unusable. I'll try to fix this today.

**Comment by georgebarbarosie** [comment]
I've checked in the database and I can confirm the issue is caused by an invalid user id (caused by manual intervention in the database).

On a side ntoe, I noticed now there are no referential integrity constraints in the database when installed as production on postgresql, I assume that's by choice.

**Comment by frenkel** [comment]
Ah, so this is not a bug in Brimir? You removed a user?
Yes, the referential integrity constraints should be added. When we started this project, there were no default foreign_keys generated by Rails.

**Comment by frenkel** [comment]
I've added foreign keys in the last commit to master, so this should not happen again.

**Comment by georgebarbarosie** [comment]
That's correct, it wasn't a bug by itself, it was caused by manual database intervention -- we deleted some of the customer users but the user IDs were left in place in the referencing tables. Thanks for the heads-up about foreign keys.
