### ISSUE TITLE
Adding new labels in UI?

### ISSUE THREAD

**Issue by georgebarbarosie** [ivaldi/brimir#273]
Hello, is there a way to add new labels from the UI? (release 0.7.0)

We can see labels can be removed, renamed, or assigned a new color from the menu but for adding labels we've had to go directly in the database. This is a minor issue for us but may be inconvenient for other users.

**Comment by frenkel** [comment]
Yes. On a ticket view, there is an add button. If you type the name of a non-existing label, it will be created for you.

**Comment by frenkel** [comment]
I'll try to add a hint in the interface, thanks for reporting this :-)

**Comment by georgebarbarosie** [comment]
Ok that makes sense. Thanks for clarifying.

**Comment by georgebarbarosie** [comment]
:thumbsup: Thanks again
