### ISSUE TITLE
Message-ID is lacking brackets on reply -- making Google remove it, in turn breaking threading

### ISSUE THREAD

**Issue by viddypiddy** [ivaldi/brimir#274]
Hi,

I've been digging around trying to figure out what is happening with "Reply"-mails from GMail not being put in the thread.

It seems google puts the Original Message-ID in the "X-Google-Original-Message-ID" header, which then can be matched against.

Is there any chance of implementing some kind of workaround (checking this Header to match the threads as well?).. 

Google having such a large part of all email suddenly makes them hard to ignore. Right now we have to merge all the replies from GMail manually, which is a pain.

**Comment by viddypiddy** [comment]
After researching even more, it seems that the message-id coming out of brimir is lacking the "<" and ">" in the start and end of the message-id on the notification emails that are sent out when replying on an existing ticket. I'm still researching why this is happening.

**Comment by viddypiddy** [comment]
I can't for the life of me figure out how "<" and ">" are disappearing.
But even in the logs before the mail is sent (production.log) the brackets are missing.
So it's being removed somewhere within the app.

Would be really nice if you took a look at this.

Here is the log showing the behavior.

<pre>
D, [2016-05-16T21:10:07.845888 #10481] DEBUG -- :
NotificationMailer#new_reply: processed outbound mail in 52.2ms
I, [2016-05-16T21:10:07.876072 #10481]  INFO -- :
Sent mail to viddy@viddy.net (29.7ms)
D, [2016-05-16T21:10:07.876239 #10481] DEBUG -- : Date: Mon, 16 May 2016 21:10:07 +0000
From: Ticket <ticket@viddy.net>
To: viddy@viddy.net
message-id: 573a372f90215_28f13f8b1556dc4c637a2@rails.mail
In-Reply-To: <573a36abcfe2c_28533fa63d7c8f44334da@rails.mail>
References: <573a174b9418c.f513fb4e636ebd0585c@rails.mail>
 <573a179fe312a-fe03f824a6a22bc373fc@rails.mail>
 <573a1aaa6a71a-fe03f824a6a22bc375d@rails.mail>
 <573a1b9896104_12d73f9960841c08854ba@rails.mail>
 <573a1d6617f1f_15cc3f91694e1b705031c@rails.mail>
 <573a22058932d_18eb3ff8d3b68f44552ce@rails.mail>
 <573a224b5f3e7_196a3fdf77f941b0815b2@rails.mail>
 <573a22842061d_19dd3f8b4181a248450ea@rails.mail>
 <573a22fb11cd8_19dd3f8b4181a24845292@rails.mail>
 <573a2cb6bb1cd_19dd3f8b4181a2484551e@rails.mail>
 <573a2e028120d_203b3fdf249201b054491@rails.mail>
 <573a2faf44d54_214a3ffc6e47b1488598d@rails.mail>
 <573a30be216d5_222f3fcc3bebb92c916f2@rails.mail>
 <573a3107f1bbd_22a53fdfe7026a7887539@rails.mail>
 <573a3132ede6f_23113fe99b9905609653f@rails.mail>
 <573a324940bc_24183f8fd6043ecc12630@rails.mail>
 <573a3499627ed_26493feea0e78a7868666@rails.mail>
 <573a3571ee686_271c3fa7a6597c4c46614@rails.mail>
 <573a3664e62c7_27de3fd8629549ec84846@rails.mail>
 <573a36abcfe2c_28533fa63d7c8f44334da@rails.mail>
<pre>

**Comment by frenkel** [comment]
Thanks for reporting this. It is now fixed in master.

**Comment by viddypiddy** [comment]
Hi. Applied the change in notification_mailer.rb, still acts the same here.
No brackets.

**Comment by viddypiddy** [comment]
Same in the production.log also.
I checked out the file from git and restarted nginx/passenger, then added a reply to an existing ticket.
This is the e-mail that god produced at that point.

<pre>`
I, [2016-05-18T12:23:34.519152 #22060]  INFO -- :   Rendered notification_mailer/new_reply.text.erb (1.5ms)
D, [2016-05-18T12:23:34.522215 #22060] DEBUG -- :
NotificationMailer#new_reply: processed outbound mail in 25.5ms
I, [2016-05-18T12:23:34.668351 #22060]  INFO -- :
Sent mail to viddy@viddy.net (145.7ms)
D, [2016-05-18T12:23:34.668476 #22060] DEBUG -- : Date: Wed, 18 May 2016 12:23:34 +0000
From: Test <ticket@viddy.net>
To: viddy@viddy.net
message-id: 573c5ec64c3d5_562c3fee6c19c6d04901a@rails.mail
In-Reply-To: <573c5a98624ef_52d43f987276fc24122af@rails.mail>
References: <5739a7c453c60_36d23fcdc35b3c242058d@rails.mail>
 <5739adc45d083_43093f87e6de68d823853@rails.mail>
 <5739add6256e8_43093f87e6de68d824040@rails.mail>
 <573c5a98624ef_52d43f987276fc24122af@rails.mail>
Subject: New reply: Henvendelse
`</pre>

**Comment by frenkel** [comment]
You're right, I fixed a different problem apparently. The fix in 278296d12134c49e032cc5d228a61a69f13ca677 does solve your problem.
