### ISSUE TITLE
Units (months, days, time etc.) not being localized

### ISSUE THREAD

**Issue by viddypiddy** [ivaldi/brimir#276]
It seems units such as days/months etc. are not being localized by just using the supplied locale files.

All the fields that seem to be lacking are available through this project:
https://github.com/svenfuchs/rails-i18n

By merging these fields into the locale/<language>.yml-file in brimir all units are translated correctly.

Just a heads up, just in case you might consider merging the locales from this project into your language files, or just link to it in your documentation so people can easier get a fully localized Brimir.

**Comment by frenkel** [comment]
Are they missing from the rails-i18n 4.0.8 gem file? Because we use that gem for translating words like this. You can download that version on https://rubygems.org/downloads/rails-i18n-4.0.8.gem and should be able to open it as a zip file.

**Comment by viddypiddy** [comment]
This gem was not installed for me, which is strange, cause it's in brimirs Gemfile. 
Thanks!
