### ISSUE TITLE
Running brimir on a sub path works -- but with some caveats

### ISSUE THREAD

**Issue by viddypiddy** [ivaldi/brimir#281]
in the HTTP-server: passenger_base_uri /brimir;
./config/environments/production.rb:  config.action_controller.relative_url_root = '/brimir/'
Setting these parameters should as far as i know have been enough.

But these changes had to be made as well:
./config/environments/production.rb:  config.tinymce.base = "/brimir/assets/tinymce"
./app/models/attachment.rb:      url: '/brimir/attachments/:id/:style',
./app/assets/javascripts/tickets.js:      url: '/brimir/labels.json',

These are the places i have found where the root was not populated correctly.
But on the other hand there are many places where this works great.

After these changes brimir works great on the sub-path.
Would have been awesome if this somehow worked out of the box. 

Thanks!

**Comment by frenkel** [comment]
Thanks for your report. We'll try to fix this in a few weeks.

**Comment by Joeasaurus** [comment]
Hi, how is this going?

**Comment by frenkel** [comment]
There's not enough interest, so we haven't worked on it. You're welcome to create a pull request for these changes though.
