### ISSUE TITLE
Exported csv contains html <span> in status column

### ISSUE THREAD

**Issue by mrmagooey** [ivaldi/brimir#283]
On a new install, using the csv export button provides a csv file where the status column contains a <span> element wrapping the status information, looking like:

    <span class="translation_missing" title="translation missing: en.open">Open</span>

I'm assuming the expected behaviour is just to contain the status information and not the wrapping span class.

**Comment by frenkel** [comment]
This can be fixed by adding a translation for "open" to the English translation. Would you be able to make a pull request for it?

**Comment by jamgregory** [comment]
I've submitted a pull request to use the `.humanize` method instead of translating it directly (as per https://richonrails.com/articles/active-record-enums-in-ruby-on-rails-4-1)

**Comment by frenkel** [comment]
Just translating all statuses in all languages is a much better fix. I think only "open" is missing in English.
