### ISSUE TITLE
how to configure ldap in brimir

### ISSUE THREAD

**Issue by csskysea** [ivaldi/brimir#288]
@frenkel 
I have configure in two files: config/ldap.yaml and config/application.rb, 
 config/application.rb,:
config.devise_authentication_strategy = :ldap_authenticatable

but in config/ldap.yaml, i 'm not sure how to configure it ,can you give a sample?thanks

**Comment by frenkel** [comment]
You'd better ask in this PR https://github.com/ivaldi/brimir/pull/167 that is the original author.
