### ISSUE TITLE
Polish localization

### ISSUE THREAD

**Issue by khtaree** [ivaldi/brimir#295]
Hello,
I'v created Polish localization for this project.
It's working correctly only when first line is set to en:
When I set it up to pl: it's crushing and web sever ish showing "We're sorry, but something went wrong."
I have no idea why. Please consider to correct this issue for me.

Best regards

[pl.zip](https://github.com/ivaldi/brimir/files/531132/pl.zip)

**Comment by frenkel** [comment]
```
translation data {:one=>"%{count} zgłoszenie", :other=>"%{count} zgłoszeń"} can not be used with :count => 3
```
Is there maybe a different word for three tickets in Polish? In English you  have one **ticket** and two or three **tickets** I think there is a difference in Polish between three and two?
