### ISSUE TITLE
Initial ticket created using web interface is missing a message_id

### ISSUE THREAD

**Issue by fauno** [ivaldi/brimir#299]
We're testing replying by email and messages get assigned to seemingly random tickets.  The issue seems to be that notification emails have empty Message-Id headers ("<>").

**Comment by frenkel** [comment]
Could you download the original message (click the save icon on the top right) and see whether the original ticket did have a message-id?

**Comment by fauno** [comment]
sorry i didn't get the notification, here you go:

From: ****@brimirapp.com
To: *****
Message-ID: <>

**Comment by frenkel** [comment]
I meant the original ticket email that was sent by somebody to the @brimirapp.com address.

**Comment by fauno** [comment]
the tickets were open from the web gui.

i have two types of email notifications:

* "ticket assigned to you" => have a message-id <xxx@brimir.mail>
* "new ticket" => empty message-id <>

**Comment by fauno** [comment]
i was looking at the code and i can't find where are the message_id's generated, so i'm guessing they're set from the original emails, but they're empty when the ticket is created from the web form? :)

**Comment by fauno** [comment]
it works when i create a ticket via email ;)

**Comment by frenkel** [comment]
This should be fixed in master.
