### ISSUE TITLE
[Feature Request]  Label assignment for agents with selected labels assigned

### ISSUE THREAD

**Issue by PewPi** [ivaldi/brimir#301]
Feature: Enabling agents, which have selected labels assigned to their agent role, to reassign tickets among those labels they can see. This may be optional and the feature can be turned on and off in the user configuration. Potentially creating both the feature of „allowing to reassign labels“ as wall as „allowing to create new labels“. Default may be „turned off“. 

We are using Brimir in a helpdesk environment for a volunteering organisation and we actually need this feature. As a team of three managing the helpdesk we would offer to commit a solution for open discussion. 

Are you interested and would you be willing to merge this feature if developed?

**Comment by frenkel** [comment]
Sure, seems like a useful feature. Let us know if you need any help during development!
