### ISSUE TITLE
trix editor: pasting links

### ISSUE THREAD

**Issue by fiedl** [ivaldi/brimir#305]
@git-jls @frenkel 

I'm just trying out the new trix editor (pull request https://github.com/ivaldi/brimir/pull/303).

The behaviour of pasting links has been changed as can bee seen in the gif below. Does anyone know if the previous behaviour can be achieved in trix as well?

![links in tinymce and trix](https://cloud.githubusercontent.com/assets/1679688/20323275/4e4cb69e-ab7c-11e6-9fd8-1c7222de922d.gif)

We often copy&paste links into replies like this:

> On [Github](https://github.com/), navigate to the [brimir](https://github.com/ivaldi/brimir) repo, click on [Issues](https://github.com/ivaldi/brimir/issues) and file a new issue by selecting [New issue](https://github.com/ivaldi/brimir/issues/new) from there.

This looks much nicer than

> On https://github.com/, navigate to the https://github.com/ivaldi/brimir repo, click on https://github.com/ivaldi/brimir/issues and file a new issue by selecting https://github.com/ivaldi/brimir/issues/new from there.

**Comment by frenkel** [comment]
Thanks for testing! Does this also happen when the insert link button has not been removed from Trix (we did that to cleanup the toolbar, but it might also disable some functionality).

**Comment by fiedl** [comment]
Unfortunately, this is the default behavior of trix as can be seen on their demo page https://trix-editor.org.

I don't know if the behavior can be changed. I don't even know how this is implemented in tiny mce.

**Comment by basschoen** [comment]
Hi Sebastian,

If I copy the link above the editor on the demo page ('Watch a video preview') and paste this in the editor, it becomes a link. However, if I copy the URL from the address bar and paste this, it doesn't automatically become a link. I'm currently using Chrome. Are you missing both the functionalities or only the latter?

**Comment by fiedl** [comment]
Hi @basschoen, 

thanks for trying this out. You're right: It apparently does work in Chrome:

![pasting-links-in-chrome](https://cloud.githubusercontent.com/assets/1679688/20339402/71e9bdc6-abdc-11e6-98bf-8485f0d9dcfa.gif)

This is how it looks in Safari:

![pasting-links-in-safari](https://cloud.githubusercontent.com/assets/1679688/20339496/ef486d8a-abdc-11e6-8058-faa5e8b02ba2.gif)

As it works with Chrome and as this seems to be an issue with trix and Safari, I'll file this as an issue in the trix repo.

As seen in the Chrome gif above, pasting links in trix in brimir does also work in Chrome. Thus, no reconfiguration is needed, @frenkel.

**Comment by frenkel** [comment]
I was just starting to like Trix... I hope they fix it for you!

**Comment by fiedl** [comment]
I'm all pro for migrating to trix. I was waiting for an opportunity to see it in action.

I've filed the issue here: https://github.com/basecamp/trix/issues/340

**Comment by fiedl** [comment]
Trix has [implemented](https://github.com/basecamp/trix/commit/6754f6c6ffecdf0dc7b6cb0e908caf9be56a6978) and [released](https://github.com/basecamp/trix/releases/tag/0.10.1) a fix: trix 0.10.1.

Now, we just have to wait for the gem to be released:
https://github.com/maclover7/trix/issues/35
