### ISSUE TITLE
[Feature Request] Just a few ideas

### ISSUE THREAD

**Issue by mickael-kerjean** [ivaldi/brimir#310]
Hello,

Thank you for creating brimir!
There's 2 missing features on Brimir that makes me stick with our current ticketing system:
1) when a user is creating a new ticket without being logged in, he might wonder if the ticket was created successfully as you don't receive any user feedback. It would be great to have a notice message so that the user knows the request has been process correctly or not
2) In its current form, I can't use Brimir across different projects/teams without going through manual labor to sort everything out and attach labels. Rules can help but it's not enough. To fix this, It would be usefull to have a label parameters in the tickets/new route so that we can craft a URL to automatically assign an existing label into the newly generated ticket. That way, we could have multiple team working on the same platform with an access to specific labels only.

Do you accept pull requests for those two features?
I already have the first  one working on my machine and I was about to try something for the second one.

**Comment by frenkel** [comment]
Hi,

1. I believe there is quite a big heading saying "ticket created"? If not, I'm wondering why you can't view it.
2. Might be useful indeed.

Yes, we do accept pull requests for those improvements. Let me know if you need any help!

**Comment by mickael-kerjean** [comment]
1. My mistake, there's a message but I was fooled trying to create a ticket without being logged in with the captcha disable. In this case I was expecting to be able to create a ticket or at least receive a message to tell me I can't do that but there's nothing like this yet. I guess it has to do with the ```TicketsController#new should be configurable as open-to-the-world or not``` written in the project README

**Comment by mickael-kerjean** [comment]
Example of a scenarios that end up with confusing behavior for a end user:

Prior: enable captcha without being logged in
1) go to /tickets/new and fill a ticket without filling the captcha
2) I'm redirected to /tickets
3) feel the captcha correctly and submit again
Result: Ticket isn't created
Expectation: The ticket can be created.
Minimum expectation: receive a message to alert the user about what's going on

Prior: disable captcha without being logged in
1) go to /tickets/new and fill a ticket
Expectation: the ticket can be created according to the configuration but user receive at the very least a feedback to know what's going on

**Comment by frenkel** [comment]
I don't understand. Are you, or are you not able to create a ticket without the captcha? Because in our setup it works fine.

**Comment by mickael-kerjean** [comment]
Without the captcha, I can only create a ticket if I'm logged in. If I'm not logged in the ticket won't be created.

**Comment by git-jls** [comment]
In response to your last comment:
I could reproduce this behavior and opened a pull request concerning this issue at [#315](https://github.com/ivaldi/brimir/pull/315)

**Comment by mickael-kerjean** [comment]
That's one of the thing my pull request was also doing. Unfortunately I didn't had time create any test for this

**Comment by frenkel** [comment]
Thanks @git-jls. 
@mickael-kerjean you can now simplify your pull request because that one bug is fixed :-)

**Comment by mickael-kerjean** [comment]
I'm not sure what you mean by simplifying the pull request? 

Do you mean that you prefer to have one big large soup in the create method instead of separating the authorization logic from the rest of the controller ?

I added 2 commits to fix 2 of your suggestions and this bug was already fixed in my previous commit [here](https://github.com/mickael-kerjean/brimir/blob/master/app/controllers/tickets_controller.rb#L218). The only difference is I was assuming that there's no need to check the captcha if you're already logged in but it generates proper messages for the end user.
