### ISSUE TITLE
[Feature Request] Add a js & css input in the settings to customize Brimir design

### ISSUE THREAD

**Issue by mickael-kerjean** [ivaldi/brimir#313]
Hello,

Would you accept a pull request for this feature?

**Comment by frenkel** [comment]
Sure, seems like a good idea to me. Could you save those in the tenants table (same as the settings screen)?

**Comment by frenkel** [comment]
BTW, maybe just CSS for now, JavaScript seems like a security issue to me (an agent might add JS to exploint another agents account),
