### ISSUE TITLE
IOS weird behavior

### ISSUE THREAD

**Issue by mickael-kerjean** [ivaldi/brimir#314]
Hello,

On IOS, when I try to submit a ticket, as soon as I focus on an input, it zoom into the field. 
I don't really like it and the fix would be simple:
```
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
```
instead of the default: 
```
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
```

**Comment by frenkel** [comment]
@smgdkngt didn't you say that locking zoom on mobile devices is a bad practice? Do you know how to fix this without zoom locking?

**Comment by smgdkngt** [comment]
There are some a11y issues with the use of maximum scale. That indeed is the reason why we've not added it (f.e. http://a11yproject.com/posts/never-use-maximum-scale/). I can't think of any other solution as this is the way the 'smart' zoom of Safari works.

Maybe add a setting for this in the user prefs?

**Comment by mickael-kerjean** [comment]
It seems like there's a sweet spot around font-size:16px in input fields that makes safari don't zoom in. Might be a option

I also saw many other articles like the one you sent arguing not to use this feature but when we look at what's the going on the internet, major players don't play by those rules: 
- github doesn't respect it (```<meta name="viewport" content="initial-scale=1.0,user-scalable=no,maximum-scale=1" media="(device-height: 568px)">```)
- google doesn't respect it (```<meta content="width=device-width,maximum-scale=1.0,initial-scale=1.0,minimum-scale=1.0,user-scalable=yes,shrink-to-fit=no" name="viewport">```)
- ebay doesn't respect it
- yahoo doesn't respect it

Only a few actually does

**Comment by mickael-kerjean** [comment]
I made a test using the 16px trick and it works way better on ios

**Comment by frenkel** [comment]
Where did you find the maximum-scale on Google pages? We haven't found any where we cannot zoom. For example: https://www.google.nl/ and https://www.google.com/calendar don't include the tag you sent.

Maybe it's better to make the fields 100% width, because we believe Safari won't zoom then.

**Comment by mickael-kerjean** [comment]
For google in Australia: <img width="1247" alt="screen shot 2016-11-26 at 6 38 50 pm" src="https://cloud.githubusercontent.com/assets/13233076/20638880/b1277a7c-b407-11e6-8699-6133903bc88c.png">

I tried with a few different real devices and always came up with the same results, pinch and zoom is disabled.

**Comment by frenkel** [comment]
Ah, you've set the user agent. Using a non mobile user agent they aren't even sending the meta viewport tag.

Well, we still can't disable it, because we have no influence on the contents of the emails. More than once I've received long texts that pass the overflow (very wide line of text) which wouldn't be readable when you disable zoom. Also, some embedded screenshots get very small and can only be made readable when you can zoom using your device.

I'm open for other solutions though. It seems Safari doesn't zoom when the input field is 100% width for example.

**Comment by mickael-kerjean** [comment]
What do you mean by an input field with a width of 100%? Removing the padding and margin?

The 16px font size solution on mobile is actually working great on mobile.

**Comment by frenkel** [comment]
Could you create a merge request with the font size in a media query? I'm willing to merge that when it doesn't break other browsers.

**Comment by mickael-kerjean** [comment]
That would do the trick. I'm a bit overwhelm by too much stuff going on this week. I'll do that as soon I got a few minutes

**Comment by frenkel** [comment]
Sure, take your time. Thanks!
