### ISSUE TITLE
Create a ticket for non logged in users

### ISSUE THREAD

**Issue by mickael-kerjean** [ivaldi/brimir#320]
When creating a new ticket, the email address field reads: 'from email address'. 
Wouldn't it be better if it reads: 'your email address' only for user that aren't logged in?

**Comment by frenkel** [comment]
Seems fine for non-logged in users indeed.

**Comment by mickael-kerjean** [comment]
That's actually a big deal for some of our users as some of them don't have a clue of what is a ticketing system, a ticket and what they should write in the from email address.

**Comment by frenkel** [comment]
Yes, it's fine if you implement this.

**Comment by mickael-kerjean** [comment]
Sure
