### ISSUE TITLE
undefined method `save_with_label' for #<Reply:0x007f5ee4ecaeb0>

### ISSUE THREAD

**Issue by fiedl** [ivaldi/brimir#327]
After a recent update, I'm getting

> A NoMethodError occurred in tickets#create:
>
 > undefined method `save_with_label' for #<Reply:0x007f5ee4ecaeb0>
 > app/controllers/tickets_controller.rb:187:in `create'

I suspect the issue being here:

In `tickets_controller#create`, `@ticket.save_with_label` is called.
https://github.com/ivaldi/brimir/blob/master/app/controllers/tickets_controller.rb#L184

But as `@ticket` is set via `TicketMailer.receive` for incoming emails, `@ticket` may be a `Reply` rather than a `Ticket`! (But `Reply#save_with_label` is not defined.)
https://github.com/ivaldi/brimir/blob/master/app/mailers/ticket_mailer.rb#L101

**Comment by frenkel** [comment]
Seems correct. Weird that we haven't experienced this in production. Would you be willing to create a PR to fix this? Or should I have a go at it?

**Comment by fiedl** [comment]
Please have a go for it. I'm on a tight schedule right now.

**Comment by frenkel** [comment]
It does occur in production, we just didn't have replies to tickets by mail. @git-jls is working on a fix, should be merged tomorrow.

**Comment by frenkel** [comment]
This was just fixed in master

**Comment by fiedl** [comment]
Great, thanks!
