### ISSUE TITLE
Assign ticket to agent – agent list not complete

### ISSUE THREAD

**Issue by ITMaulwurf1** [ivaldi/brimir#334]
Dear Brimir team,

an agent has the issue that it cannot assign tickets to all agents, only to those that are assigned to a different (!) label (the agent group that was registered very first). 

Do you have an idea how to solve this challenge?

Best regards
Carsten

**Comment by frenkel** [comment]
Thanks for your bug report. We'll try to reproduce it and when possible fix it.

@git-jls Could you take a look at this tomorrow and try to reproduce it?

**Comment by git-jls** [comment]
Hey @ITMaulwurf1, thanks for the report, I however can't seem to reproduce this behavior.

Can you perhaps send a screenshot (.gif) with your labels? Or even better tell me the steps to reproduce this issue?

**Comment by ITMaulwurf1** [comment]
Sure I will, I'm just moving to another place but will find time asap afterwards.
