### ISSUE TITLE
Support email automatically added to reply

### ISSUE THREAD

**Issue by TimoCrafter** [ivaldi/brimir#341]
Hello,
When a user sends an email to support@my.domain, a tickets is automatically being created. But when somebody replies, the email support@my.domain is in the default "notify addresses", so the ticket creator gets the notification and also the support domain, which adds it as an answer to the ticket again, so every answer is displayed twice.

I know that I can delete the support@my.domain email every time when replying, but I don't want that.

Thanks for your help,
Kind regards,
TimoCrafter

**Comment by frenkel** [comment]
You need to tadd support@my.domain to the list of email addresses in the top menu (the mail icon) in order for this to work as it should. WIth your current setup you might create mail loops.

**Comment by TimoCrafter** [comment]
Oh thank you!!!!!
