### ISSUE TITLE
key must be 32 bits

### ISSUE THREAD

**Issue by mkleins** [ivaldi/brimir#352]
## Steps to reproduce

* New installation
* Rails : 5.0.0.1
* Ruby : 2.4

## Issue

Error fatal on running

## Stacktrace 

```
F, [2017-03-09T21:49:49.814370 #28667] FATAL -- : [42be6fac-37b1-47fa-9360-987f22a7842c] ArgumentError (key must be 32 bytes):
F, [2017-03-09T21:49:49.814566 #28667] FATAL -- : [42be6fac-37b1-47fa-9360-987f22a7842c] vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.0.1/lib/active_support/message_encryptor.rb:72:in `key='
```
## Issue referenced

Rails upgrade : https://github.com/rails/rails/issues/25185

Thank you.

**Comment by frenkel** [comment]
Weird that we don't have this error in the test suite with Ruby 2.4. I've updated Rails in the master branch.
