### ISSUE TITLE
Sending new tickets to specific group via the API

### ISSUE THREAD

**Issue by jamgregory** [ivaldi/brimir#357]
We're using the API in Brimir to create new tickets from our applications when an error occurs. However, we can't set the 'to' address, which means these emails fall through the filters and end up being sent to a team that don't deal with these issues.

Is there a particular reason why the 'to' address when sending through the API? I realise that it may not be ideal for users to choose who they can send the messages to from the public front end, but for API requests, it might be useful.

Just wanted to run this by you before I considered a PR :+1:

**Comment by frenkel** [comment]
I think the API will accept a to_email_id parameter when you're signed in. If you're not signed in, it is rejected in here: https://github.com/ivaldi/brimir/blob/master/app/controllers/concerns/tickets_strong_params.rb#L36
I don't think it would be a problem to have to_email_id accepted there when not signed in, so a PR is welcomed :+1:
