### ISSUE TITLE
Capistrano for deployment

### ISSUE THREAD

**Issue by jamgregory** [ivaldi/brimir#366]
Hey @frenkel,

Would you object to a PR to include some Capistrano configuration? We normally use that to deploy our Rails apps, and it would certainly be beneficial to use to have that included.

Thanks!

**Comment by frenkel** [comment]
We use that ourselves too, but you can't make it generic enough to work for everybody, I think. For example, we don't use RVM or Rbenv on the server, but you might, so even the Capfile will differ.

**Comment by jamgregory** [comment]
I guess there could be a `Capfile.local` that is excluded from VCS but, if present, is included into the `Capfile`? Or do something similar to this which loads extra tasks:
`Dir.glob('lib/capistrano/tasks/*.rake').each { |r| import r }`

**Comment by frenkel** [comment]
Yes, and what about deploy.rb? Rvm and Rbenv sometimes also require settings in there such as the ruby version to use for that specific deploy. It will get more complex if we add all kinds of workarounds to make this generic, don't you think? You can currently create a commit which adds Capistrano with your settings and rebase that on `master` of our upstream repo which seems a lot less complex to me.

**Comment by jamgregory** [comment]
OK, that's fair enough. Would it be worth including Capistrano in the `Gemfile` at the very least? It could always be part of a separate group to be excluded if certain people don't use it?

**Comment by frenkel** [comment]
Sure, in the `:development` group it shouldn't cause any problems.
