### ISSUE TITLE
how to filter spam mail.

### ISSUE THREAD

**Issue by csskysea** [ivaldi/brimir#368]
a mail head like the following:
"X-Spam-Flag: YES
X-Spam-Score: 8.694
X-Spam-Level: ********
X-Spam-Status: Yes, score=8.694 tagged_above=0 required=5.5
 tests=[BAYES_60=1.5, DATE_IN_PAST_96_XX=3.405, HTML_MESSAGE=0.001,
 MIMEOLE_DIRECT_TO_MX=0.001, MISSING_MID=0.497, RDNS_NONE=0.793,
 TO_EQ_FM_DIRECT_MX=2.497] autolearn=no
"
if brimir has a strategy that to prevent ticket created and mail forwarding if "X-Spam-Flag: YES"? 
thanks

**Comment by frenkel** [comment]
It doesn't, but I think it should be possible to add support for this to the "Rules" component. Would you be able to create a PR for this?

**Comment by csskysea** [comment]
If brimir silently ignores the email when it finds "X-Spam-Flag=YES"
two possible solutions:
1. Brimir still create an ticket for a spam email, place it in the "Trashed" folder, but do not send notification email. Maybe we will look at the Trashed folder once a week.
2. Brimir returns a special return code (e.g. 403) on spam email and ignores it. In this case, the /usr/local/bin/brimir-post.sh script can exit with an error code. Postfix will then send a rejection email to the sender. If the sender is a valid user, he/she can contact us on alternative channel.

**Comment by frenkel** [comment]
A better solution would be what I proposed above: Extend the "Rules" component so that you can define yourself what you want to do when this header exists. Would you be able to implement this in a Pull-Request?
