### ISSUE TITLE
ticket system mailbox setup

### ISSUE THREAD

**Issue by fredtz** [ivaldi/brimir#371]
Hello Ivaldi,

As I understand you suggest to use relay postbox if software will be installed on hw/vm platform. What we have to do if we want to use docker with Brimir as main ticketing system? 
Do you have in your roadmap the setup of customized (TLS/SSL) and authorized mail box setup in most nearest future?

**Comment by frenkel** [comment]
Hello @fredtz,
What do you mean by "relay postbox"?

**Comment by fredtz** [comment]
Hello @frenkel,

As we could see from available docs there is no possibility to send email with authorization on remote mail server, currently we have to setup relay mail server w/o authorization on same host which we used for Brimir installation. But if we use docker environment it simply impossible because container already packed. Of course we could install there relay mail server too or recompose container but possibly in your roadmap already have point about setup internal system mail box as it presented in Gitlab for example
https://docs.gitlab.com/omnibus/settings/smtp.html

**Comment by frenkel** [comment]
Hello @fredtz,

Are you referring to incoming e-mail? Those can be posted from any server, you don't need to do that from you Docker container. There have been feature request to connect via IMAP or POP to a remote mailbox, but nobody has implemented that feature yet.
