### ISSUE TITLE
https access will be redirect to http access

### ISSUE THREAD

**Issue by csskysea** [ivaldi/brimir#375]
I deployed brimir and access it in internet, and let people access it via https, but i find it will always redirect to http, @frenkel  @igmarin @vrish88 do you know how to update code to keep https access?

**Comment by frenkel** [comment]
Do you use nginx? Make sure you add `proxy_set_header X-Forwarded-Proto $scheme;` to it's config, so that Rails knows it is running over HTTPS.

**Comment by csskysea** [comment]
yes , it works
