### ISSUE TITLE
404 error with all static files

### ISSUE THREAD

**Issue by jenkijo** [ivaldi/brimir#377]
I've followed Install guide in README but I get 404 error with all static files in production
[http://imgur.com/a/gYmEP](http://imgur.com/a/gYmEP)

I've run pre-compile assets
[http://imgur.com/a/i5m34](http://imgur.com/a/i5m34)

You can check this link: https://brimir-phongtruong.c9users.io/users/sign_in

**Comment by frenkel** [comment]
You're running webrick directly on that link. You should add a real webserver in front of it (like nginx or apache2) to serve the static files.
