### ISSUE TITLE
Don't send mail

### ISSUE THREAD

**Issue by jenkijo** [ivaldi/brimir#378]
Hi! I have followed this post [https://thehungrycoder.com/ruby-on-rails/integrate-sparkpost-in-your-rails-app.html](https://thehungrycoder.com/ruby-on-rails/integrate-sparkpost-in-your-rails-app.html) to integrate SparkPost in Rails, but when I created or updated ticket then no email was sent.

This is my configs:
[http://imgur.com/2cwpvSn](http://imgur.com/2cwpvSn)
[http://imgur.com/ycWIplT](http://imgur.com/ycWIplT)

**Comment by frenkel** [comment]
Brimir overwrites the settings in that last config screenshot. You should configure an email address using the interface (button in the top bar).

**Comment by jenkijo** [comment]
Hi!
I have configured an email address in Settings, but when I still didn't receive email

[http://imgur.com/N1VnTiR](http://imgur.com/N1VnTiR)
[http://imgur.com/a/7NEda](http://imgur.com/a/7NEda)

**Comment by frenkel** [comment]
Your screenshot shows the email address is not verified, which means that emails sent to that address do not end up in Brimir. Either manually verify it using something like this in the Rails console: `EmailAddress.update_all verification_token: nil` or make sure the mail is configured correctly to end up in Brimir.

**Comment by jenkijo** [comment]
Thank you, It's work
But by default, the sending email address is XXX@<domain> (in my case it is: support@my.rodex.io)
Can I change it to support@rodex.io?
I have tried modify: `config.action_mailer.default_url_options = { host: 'rodex.io' }` but it don't work

**Comment by frenkel** [comment]
That is probably an old ticket, it remembers the associated address. For new tickets it should switch to the default one (see email settings default column).

**Comment by jenkijo** [comment]
Thank you very much!
