### ISSUE TITLE
New ticket validations

### ISSUE THREAD

**Issue by fkonigy** [ivaldi/brimir#386]
Version: master

Steps to reproduce: 
* login as an agent.
* click on **New Ticket** button, then click **Create Ticket** without entering any values in the form.

Current Behavior:
* a new ticket will be created with **(No subject)** as subject and conent field will have the signature of user created the ticket, if the user has **Include quote of original message in reply** enabled. otherwise content field will be blank.

Expected Behavior:
* maybe it is better to validate these fields too:
`validates_presence_of :user_id, :content, :subject`

**Comment by frenkel** [comment]
What happens when an incoming email doesn't have some of these fields? If you want to add these validation, then only to so in the case of a web form submit.

**Comment by mftaff** [comment]
@frenkel Hey I am new-ish to Open Source contributing. Mind if I have a shot at this?
