### ISSUE TITLE
sending two many notifications when ticket creation

### ISSUE THREAD

**Issue by HaoCHEN3** [ivaldi/brimir#388]
one `ticket_received` template is set and `tenant.notify_client_when_ticket_is_created`=true.
at this time , one client creates a new ticket, new_ticket_notification will be sent to all agents and new_system_reply will be sent to all agents and user itself as well.

so both agents and users will receive two emails. Does it make sense?
Added: all system_reply emails' to_address is user email not agent's address attached

cheers

**Comment by frenkel** [comment]
Did you add the incoming email address using the button in the top menu? If not it won't recognize that it is sending mail to itself.

**Comment by HaoCHEN3** [comment]
In `admin` ui, there is a button to setup outgoing email address and no button to setup incoming address. 

possibly I did not describe the problem well. 
The case: there are 1 admin and 1 user. when the user creates a new ticket, one notification including ticket content will be sent to admin. Also, the system will create two `system_reply` notifications. The problem is both two `system_reply`'s to_address is *user email* rather than one to admin and the other to user. As I think, it makes sense if two system_reply are sent to admin and user.

**Comment by seretse** [comment]
Just thought I'd chime in too, seeing as I have the same issue. My outgoing email address is set, as per the top menu option, and all notification boxes are ticked in the settings page. The client receives two emails on a ticket being logged: once to confirm receipt, and once from the system with a "New reply: <subject>" duplicate. It would seem that the logic to recognise its own outgoing address is still problematic.
