### ISSUE TITLE
Can Brimir be installed without shell access?

### ISSUE THREAD

**Issue by PhoenixMDI** [ivaldi/brimir#390]
I want to install Brimir on my shared hosting account.  I can meet all the technical requirements but I don't have command line access, so I fall apart the moment the installation guide says I need to type a command.

Is there any way around this?  I have found a Ruby gem install interface in my CPanel, if that helps.

**Comment by frenkel** [comment]
I would'nt know how to setup a Rails application without shell access, sorry.
