### ISSUE TITLE
newbie installation question

### ISSUE THREAD

**Issue by PhoenixMDI** [ivaldi/brimir#391]
I have set up a Ruby on Rails/Ubuntu 1-click droplet on Digital Ocean for the purpose of installing Brimir.  Upon seeing that there were already files and directories on the server with the same names as those in the Brimir package, I proceeded to delete everything from the server thinking it was just a placeholder, and only after it's been deleting gems from the server-side "vendor" directory for over an hour have I realised I probably wasn't supposed to do that, since the "vendor" directory in the brimir package is virtually empty.

So given that it may be wise to scrap this droplet and start again, please can you tell me the correct way to upload these files?

Edit:  I tried installing the necessary gems and it failed.  Clearly I needed stuff that I'd deleted from the server.  So I recreated the droplet from scratch and installed the gems no problem!

Now, if I need the stuff that's on the server *and* I need the stuff from the Brimir package that suggests I need to merge the two somehow.  Please be patient as I'm a Windows user and completely out of my depth.... Is it "git pull" I need to be using??  I have tried "git pull https://github.com/ivaldi/brimir.git" but got the error "not a repository".  Am I at least on the right lines??

**Comment by frenkel** [comment]
I'm not sure what the 1 click droplet contains, but you won't need to merge their rails app with ours. You need to remove all those files, clone the Brimir repo and run the bundle command from the README to install all the needed gems.
