### ISSUE TITLE
email looping problem: Tenant email is the same as one of agents

### ISSUE THREAD

**Issue by HaoCHEN3** [ivaldi/brimir#392]
Hi,
Supposed Tenant email addr (`From`) is a@a.com, which is used to receive ticket requests by email and one of agents email addr is a@a.com. Based on this case, when a user creates a new ticket, a notification will be sent to a@a.com. At this time, when a@a.com received an email, it will create new reply(or ticket) to user while the reply will be sent as notification to a@a.com again. so there is a email loop? 

How could I solve this problem while keeping tenant and agent with the same email?

cheers

**Comment by frenkel** [comment]
That is not possible, you need to use seperate mail addresses for the agent and the incoming address.
