### ISSUE TITLE
continuous user email replies causes one thread interrupt and new ticket creation 

### ISSUE THREAD

**Issue by HaoCHEN3** [ivaldi/brimir#397]
scenario: when one agent create a new ticket for a user and the user replies the ticket twice by email, the second reply will cause a new ticket creation whose subject is with the begin if RE.

I found when birmir received the first reply, it will create a new message_id but user email client has no idea of that. Therefore, when the uses sends the second reply, the header 'In-Reply-to' does not match any ticket or reply message_id and a new ticket is created.

Does it make sense?

**Comment by frenkel** [comment]
Yes. You can use the "merge tickets" functionality for that. Select both checkboxes in the inbox for these tickets and click merge.

**Comment by HaoCHEN3** [comment]
After email reply, the email header will include references field, it is a good way to merge two emails(tickets) with one of same references?
