### ISSUE TITLE
Reply editor toolbox is misaligned

### ISSUE THREAD

**Issue by jrullmann** [ivaldi/brimir#405]
The reply editor toolbox is misaligned - it's floating to the right of the top form elements, instead of below them.

This is what I see:

<img width="1426" alt="screen shot 2017-12-30 at 11 01 55 am" src="https://user-images.githubusercontent.com/1865328/34456680-b0c9d7da-ed51-11e7-9323-92b903e5981b.png">

This is on a new installation of Brimir, with barely any configuration or data seeded.

Here's what the HTML structure looks like:

<img width="1263" alt="broken-reply" src="https://user-images.githubusercontent.com/1865328/34456685-d9836e34-ed51-11e7-8f89-ac45f813186e.png">

The grid layout looks a bit off to me, which I've annotated in the screenshot. I see columns on the same level as a paragraph element which is intended to be on a new row.

Conceptually, here's what my HTML looks like:

```
<row>
  <column/>
  <column/>
  <p/>
</row>
```

While I would expect it to look like:

```
<row>
  <column/>
  <column/>
</row>
<p/>
```

I tried changing the view to render the expected HTML, and it looked better:

<img width="1435" alt="screen shot 2017-12-30 at 11 00 24 am" src="https://user-images.githubusercontent.com/1865328/34456713-7169fb0a-ed52-11e7-9e87-bcc5d05e2fef.png">

In my test, I changed [this file](https://github.com/ivaldi/brimir/blob/master/app/views/replies/_form.html.erb#L7) to wrap rows 7-29 in a new `<div class="row"` element.

It does appear that a few other elements aren't rendering correctly, so I think a few more tweaks are needed.

Unfortunately, my employer doesn't allow me to contribute code to open source projects without a long approval process. Otherwise I would totally submit a PR!

**Comment by CyberLeo** [comment]
For some inexplicable reason, I was able to correct this by adding this bit to app/assets/stylesheets/application.scss :
`
trix-toolbar .button_row {
    border: 1px solid white;
}
`
This was a quick workaround until I could go digging through the trix gem. I'm not sure why it works; probably something with collapsing divs.

**Comment by frenkel** [comment]
Thanks for your extensive report.
There was a duplicate close div. Most of the time this can be detected viewed when using view-source, instead of the inspector.

**Comment by jrullmann** [comment]
Thanks!
