### ISSUE TITLE
Ticket answer UI broken with WYSIWYG editor (trix-toolbar)

### ISSUE THREAD

**Issue by cthiel** [ivaldi/brimir#406]
Brimir (current master) doesn't display the answer UI correctly (trix-toolbar is shifted to the right, partly off-screen) on MacOS (tried both Chrome 63 and Firefox 57).

See screenshot for example:
![image](https://user-images.githubusercontent.com/14844/34965922-da3d7a1e-fa25-11e7-8ae8-dbd8e1fc924a.png)

This issue is not present when setting "Send and receive plain text replies" is enabled for the answering agent.

**Comment by frenkel** [comment]
This was fixed a few days ago. Do you still have this with master?

**Comment by cthiel** [comment]
You are right -- I was missing a commit! Thanks!
