### ISSUE TITLE
Error at Install part: bin/rake db:schema:load RAILS_ENV=production

### ISSUE THREAD

**Issue by bforpc** [ivaldi/brimir#410]
I have everything done like described. At this part
`bin/rake db:schema:load RAILS_ENV=production` 
i get this error:

```
rake aborted!
Gem::LoadError: Specified 'postgresql' for database adapter, but the gem is not loaded. Add `gem 'pg'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).

```
I like to use mysql Database.

bfo

**Comment by frenkel** [comment]
Did you edit config/database.yml? From the README: 

> After setting up a webserver, you have to create a database for Brimir and modify the config file in config/database.yml to reflect the details.

**Comment by bforpc** [comment]
Hi,

thx for your replay. No i run into the next error:

`rake aborted!
Devise.secret_key was not set. Please add the following to your Devise initializer:

  config.secret_key = [long key]'`

Where i must put this ?
I'm not a developer.

bfo

**Comment by frenkel** [comment]
Please read the readme, it is explained there. You need to fill the secrets.yml file.

**Comment by bforpc** [comment]
Hi,

i was gone through the readme like described. 
Again, im not a developer.  I had inserted the key to the secrets.yml File with a ":"
But, I get always 
```
bin/rake db:migrate RAILS_ENV=production
rake aborted!
Devise.secret_key was not set. Please add the following to your Devise initializer:
  config.secret_key = 'long key ...'
```
After hours of probing to get this APP running I'm tyred and break now. 
WHY you make the installation process not easier?
Standard  Linux VM  from scratch (debian) and the the step by stpe procedure.

Make it like the KISS  - and you will have more user.

Bfo
