### ISSUE TITLE
Internal notes are send to customer

### ISSUE THREAD

**Issue by cimm** [ivaldi/brimir#412]
The "Reply" vs "Internal note" feature is useful. Choosing the "Internal note" radio option does not however disable or blank out the `reply_notified_user_ids` field. Even worse, it's pre-populated with the ticket reporter's address, probably the customer.

This means that the internal note will, in most cases, be send to the customer _by default_. This seems wrong, I expect an internal not to never be shared with the customer since it might include sensitive details.

Wouldn't it be safer to hide, blank out, or remove non agent addresses from the `reply_notified_user_ids` field?

**Comment by jamgregory** [comment]
@cimm - unless I'm mistaken, clicking the 'Internal note' field does blank out the field that usually has the reply addresses to it? We've certainly not experienced this in our use of Brimir.

**Comment by lostapathy** [comment]
I seem to be having the same issue as @simm - running off current version of the code.  @jamgregory are you running the latest or any chance you're on a slightly older version?

**Comment by jamgregory** [comment]
@lostapathy - we're running a slightly older version, yeah - newer than the latest release, but not the latest version on `master`.

**Comment by lostapathy** [comment]
thanks - I think there was a regression in this. Looks like I get a 500 on an ajax call when you make an internal note, I bet that's the root of it.  Will look into it next week.
