### ISSUE TITLE
Internal Server error on MAILER-DAEMON mail

### ISSUE THREAD

**Issue by cthiel** [ivaldi/brimir#413]
I'm getting
```
NoMethodError (undefined method `first' for nil:NilClass):
app/mailers/ticket_mailer.rb:87:in `receive'
app/controllers/tickets_controller.rb:179:in `create'
```
from time to time, which seem to be triggered by mails like these:
```Parameters: {"message"=>"From MAILER-DAEMON  Tue Feb 27 23:22:59 2018\n ... }```

It would be great to not fail in cases like these and still make the mail/ticket available.

**Comment by lostapathy** [comment]
FWIW, I have also seen this type of error when running version 2.7.0 of the mail gem, see #422

**Comment by cthiel** [comment]
Seems like master was downgraded to mail 2.6.6 -- let's see if the error comes back.
