### ISSUE TITLE
new user type: admin

### ISSUE THREAD

**Issue by arjhun** [ivaldi/brimir#414]
So I just installed brimir, I love it for it's simplicity and clean interface. I think it could really benefit from seperating agent roles from administrative roles. In my case the people that will be replying to tickets should not be in charge of creating users, changing email settings etc. agents should be able to be limited in what they can do within the ticketing system by administrators on different levels. I'm not saying that brimir needs a ton of extra features, but for example let an agent only respond to tickets would be a great start! Is this something that is in the pipeline or something that I'm maybe overlooking?

Thanks!

**Comment by frenkel** [comment]
There is no support for that indeed, but we'll be happy to merge a pull request for it if you have the time to build it.
