### ISSUE TITLE
Ruby recommended version?

### ISSUE THREAD

**Issue by nicolasguzca** [ivaldi/brimir#417]
Hi! Trying to install on Amazon Linux with  Ruby  2.5.1. but fails terribly. What is the recommended version of Ruby?

Thank you!

**Comment by frenkel** [comment]
Tests run agains these versions: https://github.com/ivaldi/brimir/blob/master/.travis.yml#L17
But we've only used it in production against 2.2 and 2.3

**Comment by nicolasguzca** [comment]
Thanks! 2.3 worked perfectly
