### ISSUE TITLE
Problem with merges tickets

### ISSUE THREAD

**Issue by Keni** [ivaldi/brimir#423]
ActionController::ParameterMissing in Tickets::SelectedController#update

param is missing or the value is empty: ticket
```
42	def ticket_params
43	 params.require(:ticket).permit(:status)
44	end
45	def merge?
```

**Comment by frenkel** [comment]
How can I reproduce this?

**Comment by Keni** [comment]
I select 2 tickets and click merge

**Comment by Keni** [comment]
my fail
