### ISSUE TITLE
customer is not able to reply via email

### ISSUE THREAD

**Issue by bolom** [ivaldi/brimir#427]
Hi

I have notice when the customer reply to a ticket via email, his response is not added to the ticket's history. It's normal?

thanks

**Comment by frenkel** [comment]
If you configure incoming email correctly, it should appear as reply. Does it appear as a seperate ticket?

**Comment by bolom** [comment]
we have setuped the incoming email, however when the customer reply via email,  we don't see anything in brimir.

The email is sent directly to the agent's email

**Comment by maratgaliev** [comment]
Hey, I've added brimir to /etc/aliases, and it works and create ticket, when I run from server console:
`echo "mail body here" | mail -s "mail subject here" brimir@mesbesoinsmoto.com`
After adding comments we got loop with emails from contact@brimir@mesbesoinsmoto.com

**Comment by frenkel** [comment]
You have to add your outgoing email address via the email address menu option at the top to prevent the loop.
@bolom do you see anything in your email logs? What about the production.log of Brimir?

**Comment by maratgaliev** [comment]
@frenkel can you please explain some question and help me configure correct sending incoming/outgoing settings:
1) I have contact@domain.com setted up in my Sendgrid account
2) I have user with contact@domain.com email in my brimir installation
3) I don't have user with brimir@domain.com in my Sendgrid account
4) I didn't setup any entries in my outgoing emails menu
5) I have setup sendmail to work with Brimir with my contact@domain.com credentials
6) I have setup options in config:
` config.action_mailer.default_options = { from: 'contact@domain.com' }`

Can you please advice what and how I need to setup to make in work?

Many thanks!

**Comment by bolom** [comment]
> You have to add your outgoing email address via the email address menu option at the top to prevent the loop.

outgoing email and incoming should be the same?

**Comment by bolom** [comment]
@frenkel can you reopen the issue btw?

**Comment by frenkel** [comment]
Yes, outgoing email and incoming should be the same.
