### ISSUE TITLE
Invalid delivery method :letter_opener

### ISSUE THREAD

**Issue by Moji00f** [ivaldi/brimir#431]
Hi guys
when I create a new ticket I've gotten an error 'Invalid delivery method :letter_opener`

`
Extracted source (around line #164):
       headers['Message-ID'] = "<#{ticket.message_id}>" 
    end     
    mail(to: ticket.assignee.email, subject:         
    'Ticket assigned to you: ' + ticket.subject, from: ticket.reply_from_address)   
 end`
Rails.root: /opt/bk

Application Trace | Framework Trace | Full Trace
app/mailers/notification_mailer.rb:164:in `assigned'
app/mailers/notification_mailer.rb:47:in `incoming_message'
app/controllers/tickets_controller.rb:253:in `notify_incoming'
app/controllers/tickets_controller.rb:190:in `create'

Request
Parameters:
`
{"utf8"=>"✓",
 "authenticity_token"=>"Snc04jSpe/epEP1nNMMqUPTJxJ+C+PYGphBwrQ9vdqPe+0VLx5+IMJmGqcFKJYIPVaHQqQnXbWZND4XbTE1uDg==",
 "ticket"=>{"content_type"=>"html", "from"=>"moji.ahmadi87@yahoo.com", "to_email_address_id"=>"", "subject"=>"bugs", "assignee_id"=>"", "priority"=>"unknown", "content"=>"<div>test</div>"},
 "commit"=>"Create Ticket"}
`

Response
Headers:
`
None
`

**Comment by frenkel** [comment]
You're running brimir in development mode, you should use the production environment.
