### ISSUE TITLE
Split ticket is broken

### ISSUE THREAD

**Issue by svoop** [ivaldi/brimir#447]
### Steps to Reproduce (Master Branch)

1. Create a new ticket
2. Add two replies to the ticket
3. Hit the "Split off ticket" link

### Result

<img width="680" alt="screen shot 2018-10-11 at 15 23 32" src="https://user-images.githubusercontent.com/7255/46807196-aa773780-cd69-11e8-9f50-39b2379cd43e.png">

@fiedl ping

**Comment by fiedl** [comment]
You are right, @svoop. 

This is due to a merge error on my end. To resolve this, the line

    text_content: self.text_content,

needs to be removed.

I didn't notice this issue, because I have https://github.com/ivaldi/brimir/pull/216 already merged and #216 adds the `text_content` attribute.
