### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by SpagMonster** [ivaldi/brimir#75]
It'd be nice if there were easier to use installation instructions. I've not used many Ruby applications so it is kinda a turn off. Whenever I look at Brimir I'm like damn why am I not using this? and every time the answer is -- the documentation sucks.

Just a small request!

**Comment by hawkdavis** [comment]
what should the apache.conf look like?  I followed the instructions and its just and index :(

**Comment by frenkel** [comment]
https://www.phusionpassenger.com/documentation/Users%20guide%20Apache.html#_deploying_to_a_virtual_host_8217_s_root

You probably didn't use the `public` dir as the document root?
