### ISSUE TITLE
Ticket creation crashes

### ISSUE THREAD

**Issue by JanneMantyharju** [ivaldi/brimir#91]
Seems to be related on results returned by identify

Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/c7112990471ba24eabb4db3722db089620140925-53916-1rutoz.PDF[0]$

Received mail (5303.2ms)
Completed 500 Internal Server Error in 5378ms

FloatDomainError (NaN):
  app/mailers/ticket_mailer.rb:133:in `block in receive'
  app/mailers/ticket_mailer.rb:121:in`each'
  app/mailers/ticket_mailer.rb:121:in `receive'
  app/controllers/tickets_controller.rb:133:in`block (2 levels) in create'
  app/controllers/tickets_controller.rb:108:in `create'

**Comment by Mayccoll** [comment]
Hi, I'm having the same problem on Ubuntu server 14.04
Hi, I'm having the same issue :( 
I try to install imagemagick 6.8.9 cuz i have 6.7.7 but i get an error installing.
This is what I'm doing so far to install brimir.
https://github.com/Mayccoll/Utils/tree/master/brimir
Tnks

**Comment by Mayccoll** [comment]
sorry my bad,
i was not setting this variables :)

```
config.action_mailer.default_options = { from: 'brimir@yoururl.com' }
config.action_mailer.default_url_options = { host: 'brimir.yoururl.com' }
```
